#+STARTUP: overview
#+TITLE: Johan Widéns Emacs
#+CREATOR: Johan Widén
#+LANGUAGE: en
#+OPTIONS: num:nil
#+ATTR_HTML: :style margin-left: auto; margin-right: auto;
Place your private configuration here! Remember, you do not need to run 'doom sync' after modifying this file!
* Doom doc from original config.el
Here are some additional functions/macros that could help you configure Doom:

- `load!' for loading external *.el files relative to this one
- `use-package!' for configuring packages
- `after!' for running code after a package has loaded
- `add-load-path!' for adding directories to the `load-path', relative to
  this file. Emacs searches the `load-path' when you load packages with
  `require' or `use-package'.
- `map!' for binding new keys

To get information about any of these functions/macros, move the cursor over
the highlighted symbol at press 'K' (non-evil users must press 'C-c c k').
This will open documentation for it, including demos of how they are used.

You can also try 'gd' (or 'C-c c d') to jump to their definition and see how
they are implemented.

* elisp header
  :PROPERTIES:
  :ID:       ce5fb12b-428c-40d6-b6d6-c85f30524478
  :END:
#+BEGIN_SRC emacs-lisp
;;; $DOOMDIR/config.el -*- lexical-binding: t; -*-
#+END_SRC
* My account settings
  :PROPERTIES:
  :ID:       dfbd2356-a8a4-447e-bf31-b48c4434f209
  :END:
Some functionality uses this to identify you, e.g. GPG configuration, email clients, file templates and snippets.
#+BEGIN_SRC emacs-lisp
(setq user-full-name "Johan Widén"
      user-mail-address "j.e.widen@gmail.com")
#+END_SRC
* Incremental search
  :PROPERTIES:
  :ID:       8b8193ed-9345-4580-be12-0189d9027ba7
  :END:
Settings copied from jethrokuan. Untested by me
#+BEGIN_SRC emacs-lisp
(setq search-highlight t
      search-whitespace-regexp ".*?"
      isearch-lax-whitespace t
      isearch-regexp-lax-whitespace nil
      isearch-lazy-highlight t
      isearch-lazy-count t
      lazy-count-prefix-format " (%s/%s) "
      lazy-count-suffix-format nil
      isearch-yank-on-move 'shift
      isearch-allow-scroll 'unlimited)
#+END_SRC
* Fonts
  :PROPERTIES:
  :ID:       a37bafe0-8279-40d3-b4c7-00594c2d4241
  :END:
TODO: Fix modus-vivendi font scaling, determine which fonts I actually want to use

Doom exposes five (optional) variables for controlling fonts in Doom. Here
are the three important ones:
- `doom-font'
- `doom-variable-pitch-font'
- `doom-big-font' -- used for `doom-big-font-mode'; use this for presentations or streaming.

They all accept either a font-spec, font string ("Input Mono-12"), or xlfd
font string. You generally only need these two:
(setq doom-font (font-spec :family "monospace" :size 12 :weight 'semi-light)
      doom-variable-pitch-font (font-spec :family "sans" :size 13))
#+BEGIN_SRC emacs-lisp
(setq doom-font (font-spec :family "Ubuntu Mono" :size 18)
      ;; doom-font (font-spec :family "Iosevka" :size 16)
      doom-variable-pitch-font (font-spec :family "Overpass" :size 15)
      ;;doom-variable-pitch-font (font-spec :family "FiraGO" :size 15)
      ;;doom-variable-pitch-font (font-spec :family "Libre Baskerville" :height 1.0)
      ;;doom-serif-font (font-spec :family "Libre Baskerville" :height 1.0)
      )
(set-face-attribute 'default nil :font "Ubuntu Mono-18")
;;(set-face-attribute 'default nil :font "Iosevka-16")
(set-face-attribute 'fixed-pitch nil :family "Ubuntu Mono" :height 1.0)
;;(set-face-attribute 'fixed-pitch nil :family "Iosevka" :height 1.0)
(set-face-attribute 'variable-pitch nil :family "Overpass" :height 1.0)
;;(set-face-attribute 'variable-pitch nil :family "FiraGO" :height 1.0)
;;(set-face-attribute 'variable-pitch nil :family "Libre Baskerville" :height 1.0)
(custom-set-faces!
  '(aw-leading-char-face
    :foreground "white" :background "red"
    :weight bold :height 2.5 :box (:line-width 10 :color "red")))
#+END_SRC
* Fontaine
#+BEGIN_SRC emacs-lisp
;; The concise one which relies on "implicit fallback values"
(setq fontaine-presets
      '((tiny
         :default-family "Iosevka Comfy Wide Fixed"
         :default-height 70)
        (small
         :default-family "Iosevka Comfy Fixed"
         :default-height 90)
        (regular
         :default-height 100)
        (source-code
         :default-family "Source Code Pro"
         :variable-pitch-family "Source Sans Pro"
         :default-height 110
         :bold-weight semibold)
        (medium
         :default-weight semilight
         :default-height 140)
        (large
         :default-weight semilight
         :default-height 180
         :bold-weight extrabold)
        (t ; our shared fallback properties
         :default-family "Iosevka Comfy"
         :default-weight normal
         :variable-pitch-family "Iosevka Comfy Duo"
         ;; :variable-pitch-family "FiraGO"
         :variable-pitch-height 1.05)))

(use-package! fontaine
  ;; :config
  ;; (fontaine-restore-latest-preset)

  ;; ;; Set `fontaine-recovered-preset' or fall back to desired style from
  ;; ;; `fontaine-presets'.
  ;; (if-let ((state fontaine-recovered-preset))
  ;;     (fontaine-set-preset state)
  ;;   (fontaine-set-preset 'regular))

  ;; ;; The other side of `fontaine-restore-latest-preset'.
  ;; (add-hook 'kill-emacs-hook #'fontaine-store-latest-preset)
  )
#+END_SRC
* theme
  :PROPERTIES:
  :ID:       ac9acb11-2e16-4940-b68b-e567359a9f59
  :END:
There are two ways to load a theme. Both assume the theme is installed and
available. You can either set `doom-theme' or manually load a theme with the
`load-theme' function. This is the default:
(setq doom-theme 'doom-one)
#+BEGIN_SRC emacs-lisp
(use-package! modus-themes
  :ensure
  :init
  ;; Add all your customizations prior to loading the themes
  (setq modus-themes-completions
        (quote ((matches . (extrabold background intense))
                (selection . (semibold accented intense))
                (popup . (accented)))))
  (setq modus-themes-mixed-fonts t)
  ;; (setq modus-themes-italic-constructs t
  ;;       modus-themes-bold-constructs nil
  ;;       modus-themes-region '(bg-only no-extend))

  ;; Load the theme files before enabling a theme
  (modus-themes-load-themes)
  :config
  ;; Load the theme of your choice:
  (modus-themes-load-vivendi) ;; OR (modus-themes-load-operandi)
  (setq doom-theme 'modus-vivendi)
  ;; :bind ("<f5>" . modus-themes-toggle)
  )
#+END_SRC
** Switch themes (github-alphapapa)
:PROPERTIES:
:ID:       5ae6e18a-fa30-4d8e-8d6d-0fbc3695ab47
:END:
For users of counsel, the second one is already implemented, as counsel-load-theme-action (non-interactive version) or counsel-load-theme (with completion).
#+BEGIN_SRC emacs-lisp
(defun ap/load-doom-theme (theme)
  "Disable active themes and load a Doom theme."
  (interactive
   (list (intern (completing-read
                  "Theme: " (->> (custom-available-themes)
                              (-map #'symbol-name)
                              (--select (string-prefix-p "doom-" it)))))))
  (ap/switch-theme theme))

(defun ap/switch-theme (theme)
  "Disable active themes and load THEME."
  (interactive
   (list (intern (completing-read
                  "Theme: " (mapcar #'symbol-name (custom-available-themes))))))
  (mapc #'disable-theme custom-enabled-themes)
  (load-theme theme 'no-confirm))
#+END_SRC
* Load =.secret.el=
  :PROPERTIES:
  :ID:       09f7fbb1-48e9-4f32-9be4-39c8f981d7ae
  :END:
I load =~/.emacs.d/.secret.el= to keep sensible things out of version control.
For instance, you could set your identity by customizing both =user-full-name=
and =user-mail-address=. This is also where you want your API tokens to live.

#+BEGIN_SRC emacs-lisp :results silent
(defvar jw/paradox-github-token nil)

(let ((secret.el (expand-file-name ".secret.el" "~")))
  (when (file-exists-p secret.el)
    (load secret.el)))
#+END_SRC
* server
  :PROPERTIES:
  :ID:       fbd70f3b-b2a3-4d7d-9396-e8d62e779508
  :END:
Allow emacs to run as a daemon
#+BEGIN_SRC emacs-lisp
(server-start)
#+END_SRC
* Better defaults
  :PROPERTIES:
  :ID:       903cb89e-f84c-4bab-8b65-183c03bb7af0
  :END:
** My defaults
   :PROPERTIES:
   :ID:       33c7db76-5c8e-445b-99f1-5fcdb0bf38d6
   :END:
#+BEGIN_SRC emacs-lisp
(setq-default
 help-window-select t             ; Focus new help windows when opened
 ;;debug-on-error t
 ;;jit-lock-defer-time 0
 ;;fast-but-imprecise-scrolling t ; Set by doom
 ;;sentence-end-double-space nil    ; End a sentence after a dot and a space. Set by doom
 window-combination-resize t      ; Resize windows proportionally
 history-delete-duplicates t
 next-error-message-highlight t
 completions-detailed t
 describe-bindings-outline t
 calc-make-windows-dedicated t
 )
(after! recentf (setq recentf-max-saved-items 1000))
#+END_SRC
** lolsmacs
   :PROPERTIES:
   :ID:       3c68f97c-2461-4d6a-9a66-80c039134b16
   :END:
Many settings in lolsmacs are already handled in doom.
The doom settings are probably better. I just copy a few settings from lolsmacs.
I want to avoid desktop, which is turned on in lolsmacs.
#+BEGIN_SRC emacs-lisp
(global-auto-revert-mode t)
#+END_SRC
* macro defkeys
From https://github.com/amno1/.emacs.d/blob/main/init.org
#+BEGIN_SRC emacs-lisp
(defmacro defkeys (mapname &rest body)
  `(let ((defs '(,@body)))
     (while defs
       (define-key ,mapname
                   (if (vectorp (car defs))
                       (car defs)
                     (read-kbd-macro (car defs)))
                   (if (or (listp (cadr defs)) (functionp (cadr defs)))
                       (cadr defs)
                     (if `(keymapp (bound-and-true-p ,(cadr defs)))
                         (eval (cadr defs)))))
       (setq defs (cddr defs)))))
#+END_SRC

* projectile
:PROPERTIES:
:ID:       38c69c0e-172b-419a-99e7-2b71bd77c0a5
:END:
#+BEGIN_SRC emacs-lisp
(require 'projectile)
(projectile-global-mode)
(setq projectile-enable-caching t)
(setq projectile-switch-project-action #'projectile-dired) ; Was +workspaces-set-project-action-fn
#+END_SRC
* org
  :PROPERTIES:
  :ID:       fff596b9-2ad3-4e12-9a6e-0ebbfc92a861
  :END:
** org proper
   :PROPERTIES:
   :ID:       77b3098f-80b3-4460-9ec1-136da8238715
   :END:
If you use `org' and don't want your org files in the default location below,
change `org-directory'. It must be set before org loads!
#+BEGIN_SRC emacs-lisp
(setq org-directory "~/org/")
(setq org-use-speed-commands t)
(setq org-attach-id-dir "~/org/attachments/")
#+END_SRC
** Agenda
   :PROPERTIES:
   :ID:       870049d3-822d-4b71-9893-e36007769341
   :END:
#+BEGIN_SRC emacs-lisp
(require 'find-lisp)

(setq jethro/org-agenda-directory (file-truename "~/org-files/"))
(setq org-agenda-files
      (find-lisp-find-files jethro/org-agenda-directory "\.org$"))

(use-package! org-agenda
  :init
  (setq org-agenda-block-separator nil
        org-agenda-start-with-log-mode t)
  (defun jethro/switch-to-agenda ()
    (interactive)
    (org-agenda nil " "))
  :bind (:map org-agenda-mode-map
              ("i" . org-agenda-clock-in)
              ("r" . jethro/org-process-inbox)
              ("R" . org-agenda-refile)
              ("c" . jethro/org-inbox-capture))
  :config
  (setq org-columns-default-format "%40ITEM(Task) %Effort(EE){:} %CLOCKSUM(Time Spent) %SCHEDULED(Scheduled) %DEADLINE(Deadline)")
  (setq org-agenda-custom-commands `((" " "Agenda"
                                      ((agenda ""
                                               ((org-agenda-span 'week)
                                                (org-deadline-warning-days 365)))
                                       (todo "TODO"
                                             ((org-agenda-overriding-header "To Refile")
                                              (org-agenda-files '(,(concat jethro/org-agenda-directory "inbox.org")))))
                                       (todo "TODO"
                                             ((org-agenda-overriding-header "Emails")
                                              (org-agenda-files '(,(concat jethro/org-agenda-directory "emails.org")))))
                                       (todo "NEXT"
                                             ((org-agenda-overriding-header "In Progress")
                                              (org-agenda-files '(,(concat jethro/org-agenda-directory "someday.org")
                                                                  ,(concat jethro/org-agenda-directory "projects.org")
                                                                  ,(concat jethro/org-agenda-directory "next.org")))
                                              ))
                                       (todo "TODO"
                                             ((org-agenda-overriding-header "Projects")
                                              (org-agenda-files '(,(concat jethro/org-agenda-directory "projects.org")))
                                              ))
                                       (todo "TODO"
                                             ((org-agenda-overriding-header "One-off Tasks")
                                              (org-agenda-files '(,(concat jethro/org-agenda-directory "next.org")))
                                              (org-agenda-skip-function '(org-agenda-skip-entry-if 'deadline 'scheduled)))))))))

(defun jethro/org-archive-done-tasks ()
  "Archive all done tasks."
  (interactive)
  (org-map-entries 'org-archive-subtree "/DONE" 'file))

(after! org (progn
              (add-to-list
               'org-capture-templates
               `("P" "Protocol" entry (file+headline ,(concat org-directory "notes.org") "Inbox")
                 "* %^{Title}\nSource: %u, %c\n #+BEGIN_QUOTE\n%i\n#+END_QUOTE\n\n\n%?"))
              (add-to-list
               'org-capture-templates
               `("L" "Protocol Link" entry (file+headline ,(concat org-directory "notes.org") "Inbox")
                 "* %? [[%:link][%:description]] \nCaptured On: %U"))
              (add-to-list
               'org-capture-templates
               `("l" "Link" entry (file+headline ,(concat org-directory "notes.org") "Links")
                 "* %a %^g\n %?\n %T\n %i"))
              (add-to-list
               'org-capture-templates
               `("w" "Web site" entry (file "")
                 "* %a :website:\n\n%U %?\n\n%:initial"))
              ))

(setq org-todo-keywords
      '((sequence "TODO(t)" "NEXT(n)" "|" "DONE(d)")
        (sequence "WAITING(w@/!)" "HOLD(h@/!)" "|" "CANCELLED(c@/!)")))

(setq org-log-done 'time
      org-log-into-drawer t
      org-log-state-notes-insert-after-drawers nil)

(setq org-tag-alist (quote (("@errand" . ?e)
                            ("@office" . ?o)
                            ("@home" . ?h)
                            (:newline)
                            ("CANCELLED" . ?c))))

(setq org-fast-tag-selection-single-key nil)
(setq org-refile-use-outline-path 'file
      org-outline-path-complete-in-steps nil)
(setq org-refile-allow-creating-parent-nodes 'confirm
      org-refile-targets '((org-agenda-files . (:level . 1))))

(defvar jethro/org-agenda-bulk-process-key ?f
  "Default key for bulk processing inbox items.")

(defun jethro/org-process-inbox ()
  "Called in org-agenda-mode, processes all inbox items."
  (interactive)
  (org-agenda-bulk-mark-regexp "inbox:")
  (jethro/bulk-process-entries))

(defvar jethro/org-current-effort "1:00"
  "Current effort for agenda items.")

(defun jethro/my-org-agenda-set-effort (effort)
  "Set the EFFORT property for the current headline."
  (interactive
   (list (read-string (format "Effort [%s]: " jethro/org-current-effort) nil nil jethro/org-current-effort)))
  (setq jethro/org-current-effort effort)
  (org-agenda-check-no-diary)
  (let* ((hdmarker (or (org-get-at-bol 'org-hd-marker)
                       (org-agenda-error)))
         (buffer (marker-buffer hdmarker))
         (pos (marker-position hdmarker))
         (inhibit-read-only t)
         newhead)
    (org-with-remote-undo buffer
      (with-current-buffer buffer
        (widen)
        (goto-char pos)
        (org-show-context 'agenda)
        (funcall-interactively 'org-set-effort nil jethro/org-current-effort)
        (end-of-line 1)
        (setq newhead (org-get-heading)))
      (org-agenda-change-all-lines newhead hdmarker))))

(defun jethro/org-agenda-process-inbox-item ()
  "Process a single item in the 'org-agenda'."
  (org-with-wide-buffer
   (org-agenda-set-tags)
   (org-agenda-priority)
   (call-interactively 'jethro/my-org-agenda-set-effort)
   (org-agenda-refile nil nil t)))

(defun jethro/bulk-process-entries ()
  (if (not (null org-agenda-bulk-marked-entries))
      (let ((entries (reverse org-agenda-bulk-marked-entries))
            (processed 0)
            (skipped 0))
        (dolist (e entries)
          (let ((pos (text-property-any (point-min) (point-max) 'org-hd-marker e)))
            (if (not pos)
                (progn (message "Skipping removed entry at %s" e)
                       (cl-incf skipped))
              (goto-char pos)
              (let (org-loop-over-headlines-in-active-region) (funcall 'jethro/org-agenda-process-inbox-item))
              ;; `post-command-hook' is not run yet.  We make sure any
              ;; pending log note is processed.
              (when (or (memq 'org-add-log-note (default-value 'post-command-hook))
                        (memq 'org-add-log-note post-command-hook))
                (org-add-log-note))
              (cl-incf processed))))
        (org-agenda-redo)
        (unless org-agenda-persistent-marks (org-agenda-bulk-unmark-all))
        (message "Acted on %d entries%s%s"
                 processed
                 (if (= skipped 0)
                     ""
                   (format ", skipped %d (disappeared before their turn)"
                           skipped))
                 (if (not org-agenda-persistent-marks) "" " (kept marked)")))))

(defun jethro/org-inbox-capture ()
  "Capture a task in agenda mode."
  (interactive)
  (org-capture nil "i"))

;; (setq org-agenda-bulk-custom-functions `((,jethro/org-agenda-bulk-process-key jethro/org-agenda-process-inbox-item)))

(defun jethro/set-todo-state-next ()
  "Visit each parent task and change NEXT states to TODO."
  (org-todo "NEXT"))

;; (add-hook 'org-clock-in-hook 'jethro/set-todo-state-next 'append)

;; (use-package! org-clock-convenience
;;   :bind (:map org-agenda-mode-map
;;               ("<S-up>" . org-clock-convenience-timestamp-up)
;;               ("<S-down>" . org-clock-convenience-timestamp-down)
;;               ("o" . org-clock-convenience-fill-gap)
;;               ("e" . org-clock-convenience-fill-gap-both)))
#+END_SRC
** Which buffer types get org mode
   :PROPERTIES:
   :ID:       c9f6adc7-51b8-4a3e-92f0-97638b1b3ed4
   :END:
#+BEGIN_SRC emacs-lisp
(add-to-list 'auto-mode-alist '("\\.\\(org_archive\\|txt\\)$" . org-mode))
#+END_SRC
** org-journal
   :PROPERTIES:
   :ID:       1bad0efc-f56c-4481-b6cd-ebfefdca2229
   :END:
#+BEGIN_SRC emacs-lisp
(use-package! org-journal
;;   :defer t
  :after org
  :config
  (setq org-journal-date-prefix "#+TITLE: "
        org-journal-file-format "private-%Y-%m-%d.org"
        org-journal-dir "~/org/roam/"
        org-journal-carryover-items nil
        org-journal-date-format "%Y-%m-%d")
)
#+END_SRC
** Babel
   :PROPERTIES:
   :ID:       fa99e051-0c72-4e4f-b982-f6600e93bf98
   :END:
#+BEGIN_SRC emacs-lisp
(after! org
  (require 'ob-emacs-lisp)
  ;; (require 'ob-ledger)
  (require 'ob-python)
  (require 'ob-shell)
  (require 'ob-core)
  (require 'ob-tangle)
  (setq org-babel-load-languages '((emacs-lisp . t)
                                   (ledger . t)
                                   (python . t)
                                   (shell . t)  ; in my case /bin/bash
)))
#+END_SRC

We need to tell babel to use python3. Who uses python2 anymore anyway? And why
doesn't ~python~ refer to the latest version!?
#+BEGIN_SRC emacs-lisp
(setq org-babel-python-command "python3")
#+END_SRC
** ox-gfm
   :PROPERTIES:
   :ID:       22f49616-12d4-4ca9-89ac-fc8eb3df7acc
   :END:
#+BEGIN_SRC emacs-lisp
(after! org
  (require 'ox-gfm nil t))
#+END_SRC
** org-roam
:PROPERTIES:
:ID:       6279e719-3e34-4c47-bb70-29eab08e9c36
:END:
#+BEGIN_SRC emacs-lisp
(setq org-roam-v2-ack t)
;; (use-package! org-roam
;;  :init
  (setq org-roam-directory (file-truename "~/org/roam/")
        org-roam-db-location (file-truename "~/org/roam/org-roam.db")
        org-id-link-to-org-use-id t)
;;  )
#+END_SRC
** org-roam-ui
:PROPERTIES:
:ID:       a62b9c68-c0c1-4f41-9e14-396733af5710
:END:
#+BEGIN_SRC emacs-lisp
(use-package! websocket
    :after org-roam)

(use-package! org-roam-ui
    :after org-roam ;; or :after org
;;         normally we'd recommend hooking orui after org-roam, but since org-roam does not have
;;         a hookable mode anymore, you're advised to pick something yourself
;;         if you don't care about startup time, use
;;  :hook (after-init . org-roam-ui-mode)
    :config
    (setq org-roam-ui-sync-theme t
          org-roam-ui-follow t
          org-roam-ui-update-on-save t
          org-roam-ui-open-on-start t))
#+END_SRC
** org-roam-protocol
:PROPERTIES:
:ID:       b30bf97d-12b8-4c40-8acc-2600a7dec676
:END:
#+BEGIN_SRC emacs-lisp
(use-package! org-roam-protocol
  :after org-protocol)
#+END_SRC
** hugo-enable
BEGIN_SRC emacs-lisp
(after! (org ox-hugo)
  (defun jethro/conditional-hugo-enable ()
    (save-excursion
      (if (cdr (assoc "SETUPFILE" (org-roam--extract-global-props '("SETUPFILE"))))
          (org-hugo-auto-export-mode +1)
        (org-hugo-auto-export-mode -1))))
  (add-hook 'org-mode-hook #'jethro/conditional-hugo-enable))
END_SRC
** org-noter
:PROPERTIES:
:ID:       31e4d0a0-ede9-4087-bea3-557db2b9c856
:END:
+BEGIN_SRC emacs-lisp
(setq org-noter-always-create-frame nil
      org-noter-notes-search-path '("~/org/roam/org-noter"))
+END_SRC
** bibtex-completion
#+BEGIN_SRC emacs-lisp
(use-package! bibtex-completion
  :config
  (setq bibtex-completion-bibliography '("/home/jw/org/roam/biblio/references.bib")
        bibtex-completion-library-path "/home/jw/org/roam/pdfs"
        bibtex-completion-notes-path "/home/jw/org/roam/biblio/helm-bibtex-notes"
        bibtex-completion-notes-template-multiple-files "#+TITLE: Notes on: ${author-or-editor} (${year}): ${title}\n\nSee [cite/t:@${=key=}]\n"
        bibtex-completion-additional-search-fields '(keywords)
        bibtex-completion-display-formats
	    '((article       . "${=has-pdf=:1}${=has-note=:1} ${year:4} ${author:36} ${title:*} ${journal:40}")
	      (inbook        . "${=has-pdf=:1}${=has-note=:1} ${year:4} ${author:36} ${title:*} Chapter ${chapter:32}")
	      (incollection  . "${=has-pdf=:1}${=has-note=:1} ${year:4} ${author:36} ${title:*} ${booktitle:40}")
	      (inproceedings . "${=has-pdf=:1}${=has-note=:1} ${year:4} ${author:36} ${title:*} ${booktitle:40}")
	      (t             . "${=has-pdf=:1}${=has-note=:1} ${year:4} ${author:36} ${title:*}"))
        bibtex-completion-pdf-field "file"
        bibtex-completion-pdf-open-function 'org-open-file
))
#+END_SRC
** org-menu
#+BEGIN_SRC emacs-lisp
(use-package! org-menu
 :after org
 :config
 (define-key org-mode-map (kbd "C-c m") 'org-menu)
  )
#+END_SRC
** org-recoll
:PROPERTIES:
:ID:       cd3427e8-5b55-4317-a141-2e528f082fad
:END:
#+BEGIN_SRC emacs-lisp
(use-package! org-recoll)
#+END_SRC
** org-similarity
:PROPERTIES:
:ID:       54c02488-a6d8-42d8-9b2b-1a50ca5cd342
:END:
#+BEGIN_SRC emacs-lisp
(use-package! org-similarity
  :config
  (setq org-similarity-directory org-roam-directory)
  )
#+END_SRC
* line numbers
  :PROPERTIES:
  :ID:       b7b18ae3-e719-44f9-a0af-ec04627745c9
  :END:
This determines the style of line numbers in effect. If set to `nil', line
numbers are disabled. For relative line numbers, set this to `relative'.
#+BEGIN_SRC emacs-lisp
(setq display-line-numbers-type nil)
#+END_SRC
* Doom config documentation
  :PROPERTIES:
  :ID:       646c211a-fd8e-4b57-b7a8-ab7cfd3213b4
  :END:
Here are some additional functions/macros that could help you configure Doom:
- `load!' for loading external *.el files relative to this one
- `use-package!' for configuring packages
- `after!' for running code after a package has loaded
- `add-load-path!' for adding directories to the `load-path', relative to
  this file. Emacs searches the `load-path' when you load packages with
  `require' or `use-package'.
- `map!' for binding new keys

To get information about any of these functions/macros, move the cursor over
the highlighted symbol at press 'K' (non-evil users must press 'C-c c k').
This will open documentation for it, including demos of how they are used.

You can also try 'gd' (or 'C-c c d') to jump to their definition and see how
they are implemented.
* Helm
** helm proper
:PROPERTIES:
:ID:       0f3f620f-db2b-46c4-8891-9d4860237a80
:END:
#+BEGIN_SRC emacs-lisp
(use-package! helm
  :init
  (progn
      (require 'helm-config)
      (require 'helm-grep)
      (require 'helm-projectile)
      (define-key helm-map (kbd "<tab>") 'helm-execute-persistent-action) ; rebind tab to do persistent action
      (define-key helm-map (kbd "C-i") 'helm-execute-persistent-action) ; make TAB work in terminal
      (define-key helm-map (kbd "C-j")  'helm-select-action) ; list actions using C-z

      (setq
       ;; helm-net-prefer-curl t ; test if this works
       ;; helm-scroll-amount 4 ; scroll 4 lines other window using M-<next>/M-<prior>. Default nil, 1 is suggested
       helm-ff-search-library-in-sexp t ; search for library in `require' and `declare-function' sexp.
       helm-candidate-number-limit 150
       ;; you can customize helm-do-grep to execute ack-grep
       helm-grep-default-command "ack-grep -Hn --smart-case --no-group --no-color %e %p %f"
       helm-grep-default-recurse-command "ack-grep -H --smart-case --no-group --no-color %e %p %f"
       helm-split-window-inside-p t ; open helm buffer inside current window, not occupy whole other window
       helm-ff-file-name-history-use-recentf t
       helm-ff-auto-update-initial-value t
       helm-move-to-line-cycle-in-source t ; move to end or beginning of source when reaching top or bottom of source.
       helm-completion-style 'helm-fuzzy
       helm-buffers-fuzzy-matching t ; fuzzy matching buffer names when non-nil
                                     ; useful in helm-mini that lists buffers
       helm-buffer-skip-remote-checking t
       helm-locate-fuzzy-match t
       )
      (global-set-key (kbd "C-h b b") 'helm-descbinds)

      ;; use helm to list eshell history
      (add-hook 'eshell-mode-hook
                #'(lambda ()
                    (define-key eshell-mode-map (kbd "M-l")  'helm-eshell-history)))

      ;; show minibuffer history with Helm
      (define-key minibuffer-local-map (kbd "M-p") 'helm-minibuffer-history)
      (define-key minibuffer-local-map (kbd "M-n") 'helm-minibuffer-history)

      (helm-projectile-on)
      (setq projectile-completion-system 'helm)
      (setq projectile-indexing-method 'alien)
    )
  )
#+END_SRC

** helm-bibtex
#+BEGIN_SRC emacs-lisp
(use-package! helm-bibtex)
#+END_SRC
** helm-describe-modes
:PROPERTIES:
:ID:       aee4f068-4309-4cc1-a4ba-71a942e1670f
:END:
#+BEGIN_SRC emacs-lisp
(global-set-key [remap describe-mode] #'helm-describe-modes)
#+END_SRC
** helm-ls-git
#+BEGIN_SRC emacs-lisp
  (use-package! helm-ls-git)
#+END_SRC
** helm-pages
#+BEGIN_SRC emacs-lisp
  (use-package! helm-pages)
#+END_SRC
** helm-proc
:PROPERTIES:
:ID:       cccad4c9-601a-43fd-aead-01b20494bb32
:END:
#+BEGIN_SRC emacs-lisp
  (use-package! helm-proc)
#+END_SRC
** helm-pydoc
:PROPERTIES:
:ID:       cdd2e45b-442a-4942-80ed-1773a8e6e00c
:END:
#+BEGIN_SRC emacs-lisp
  (use-package helm-pydoc)
#+END_SRC
** helm-tramp
:PROPERTIES:
:ID:       79ee5efd-7f95-47d6-8a58-93e8a2cd8eef
:END:
#+BEGIN_SRC emacs-lisp
  (use-package helm-tramp)
#+END_SRC
** mu-helm-rg
:PROPERTIES:
:ID:       81498544-301d-467f-b170-b1c728bfdb8b
:END:
https://www.manueluberti.eu/emacs/2020/02/22/ripgrepping-with-helm/
One can also use helm-do-grep-ag
#+BEGIN_SRC emacs-lisp
  (setq helm-grep-ag-command (concat "rg"
                                     " --color=never"
                                     " --smart-case"
                                     " --no-heading"
                                     " --line-number %s %s %s")
        helm-grep-file-path-style 'relative)
  (defun mu-helm-rg (directory &optional with-types)
    "Search in DIRECTORY with RG.
  With WITH-TYPES, ask for file types to search in."
    (interactive "P")
    (require 'helm-adaptive)
    (helm-grep-ag-1 (expand-file-name directory)
                    (helm-aif (and with-types
                                   (helm-grep-ag-get-types))
                        (helm-comp-read
                         "RG type: " it
                         :must-match t
                         :marked-candidates t
                         :fc-transformer 'helm-adaptive-sort
                         :buffer "*helm rg types*"))))
  (defun mu--project-root ()
    "Return the project root directory or `helm-current-directory'."
    (require 'helm-ls-git)
    (if-let (dir (helm-ls-git-root-dir))
        dir
      (helm-current-directory)))
  (defun mu-helm-project-search (&optional with-types)
    "Search in current project with RG.
  With WITH-TYPES, ask for file types to search in."
    (interactive "P")
    (mu-helm-rg (mu--project-root) with-types))

  (defun mu-helm-file-search (&optional with-types)
    "Search in `default-directory' with RG.
  With WITH-TYPES, ask for file types to search in."
    (interactive "P")
    (mu-helm-rg default-directory with-types))
#+END_SRC
** helm-swoop
#+BEGIN_SRC emacs-lisp
  (use-package! helm-swoop)
#+END_SRC
** imenu-anywhere
#+BEGIN_SRC emacs-lisp
  (use-package! imenu-anywhere)
#+END_SRC
** insert from kill-ring
:PROPERTIES:
:ID:       50cf5b22-8878-4ad0-8384-3c60633ea8cf
:END:
#+BEGIN_SRC emacs-lisp
(defun my/helm-insert-kill-ring ()
  "Get an entry from the kill ring and insert."
  (interactive)
  (require 'helm-ring)
  (let* ((helm-kill-ring-actions '(("Get" . identity)))
         (delete-range (when (region-active-p)
                         (cons (region-beginning) (region-end))))
         (result (helm-show-kill-ring)))
    (when result
      (deactivate-mark)
      (when delete-range
        (goto-char (car delete-range))
        (delete-char (- (cdr delete-range) (car delete-range))))
      (insert (substring-no-properties result)))))
#+END_SRC
** org-ql
#+BEGIN_SRC emacs-lisp
(use-package! org-ql)
(use-package! helm-org-ql)
#+END_SRC
** helm-org-rifle
#+BEGIN_SRC emacs-lisp
(use-package! helm-org-rifle)
#+END_SRC
** helm key bindings in C-z map
Rebind C-z, by default it is suspend-frame
From https://github.com/amno1/.emacs.d/blob/main/init.org
#+BEGIN_SRC emacs-lisp
(define-prefix-command 'C-z-map)
(global-set-key (kbd "C-z") 'C-z-map)
(defkeys global-map
       "C-z ,"   helm-pages
       "C-z C-b" helm-buffers-list
       "C-z a"   mu-helm-project-search
       "C-z b"   helm-filtered-bookmarks
       "C-z c"   helm-company
       "C-z d"   helm-dabbrev
       "C-z e"   helm-calcul-expression
       "C-z g"   helm-google-suggest
       "C-z h"   helm-descbinds
       "C-z i"   helm-imenu-anywhere
       "C-z k"   helm-show-kill-ring
       "C-z f"   helm-find-files
       "C-z m"   helm-mini
       "C-z o"   helm-occur
       "C-z p"   helm-browse-project
       "C-z q"   helm-apropos
       "C-z r"   helm-recentf
       "C-z s"   helm-swoop
       "C-z C-c" helm-colors
       "C-z x"   helm-M-x
       "C-z y"   helm-yas-complete
       "C-z C-g" helm-ls-git-ls
       "C-z SPC" helm-all-mark-rings)
#+END_SRC
* citeproc
#+BEGIN_SRC emacs-lisp
(use-package! citeproc)
(use-package! oc
  :config
  (require 'oc-csl))
(use-package! org-ref-cite-core)
(use-package! org-ref-cite
  :config
  ;; I like green links
  (set-face-attribute 'org-cite nil :foreground "DarkSeaGreen4")
  (set-face-attribute 'org-cite-key nil :foreground "forest green")
  (setq
   org-cite-global-bibliography bibtex-completion-bibliography
   ;; https://github.com/citation-style-language/styles
   ;; or https://www.zotero.org/styles
   org-cite-csl-styles-dir "/home/jw/Zotero/styles"
   org-cite-insert-processor 'org-ref-cite
   org-cite-follow-processor 'org-ref-cite
   org-cite-activate-processor 'org-ref-cite
   org-cite-export-processors '((html csl "elsevier-with-titles.csl")
			        (latex org-ref-cite)
			        (t basic)))

  (define-key org-mode-map (kbd "C-c \\") 'org-cite-insert))
#+END_SRC
* exwm-randr
:PROPERTIES:
:ID:       57969c61-76ac-408b-8895-9da84587e280
:END:
#+BEGIN_SRC emacs-lisp
  (use-package! exwm)
  (require 'exwm-randr)
  (defun jw/env-list (env-string)
      "Return list of strings in environment variable env-string.
  nil if empty or undefined."
      (let ((env-var (getenv env-string)))
        (if env-var
            (split-string env-var)
          nil)))
  (defun jw/env-str (env-string)
      "Return string in environment variable env-string.
  nil if empty or undefined."
      (let ((env-var (getenv env-string)))
        (if (> (length env-var) 0)
            env-var
          nil)))

    (defun jw/build-workspace-monitor-plist (list)
      (let (transformed-list first second (rev-list (reverse list)))
        (while rev-list
          (setq second (car rev-list))
          (setq first (string-to-number (car (cdr rev-list))))
          (setq transformed-list (cons first (cons second transformed-list)))
          (setq rev-list (cdr (cdr rev-list)))
          )
        transformed-list))

    (defun jw/xrandr-output-list ()
      "Return list of connected X11 screens, according to xrandr."
      (interactive)
      (let* ((xrandr-output-regexp "\n\\([^ ]+\\) connected ")
             (find-outputs
              (lambda ()
                (let (output-list)
                  (call-process "/usr/bin/xrandr" nil t nil)
                  (goto-char (point-min))
                  (while (re-search-forward xrandr-output-regexp nil 'noerror)
                    (setq output-list (cons (match-string 1) output-list))
                    (forward-line))
                  (reverse output-list))))
             (output-list (with-temp-buffer
                            (funcall find-outputs))))
         output-list))

    (setq jw/x11-screen-list (jw/env-list "X11_SCREEN_LIST"))
    (setq jw/x11-screen-order-list (jw/env-list "X11_SCREEN_ORDER_LIST"))
    (setq jw/x11-screen-mode-list (jw/env-list "X11_SCREEN_MODE_LIST"))
    (setq jw/x11-screen-rate-list (jw/env-list "X11_SCREEN_RATE_LIST"))
    (setq jw/x11-screen-disabled-list (jw/env-list "X11_SCREEN_DISABLED_LIST"))
    (setq jw/exwm-workspace-list (jw/env-list "EXWM_WORKSPACE_LIST"))
    (setq jw/x11-screen-preferred (jw/env-str "X11_SCREEN_PREFERRED"))
    (setq jw/x11-display-dpi (jw/env-str "X11_DISPLAY_DPI"))
    (let ((env-var (getenv "X11_SCREEN_USE_ALL_AVAILABLE")))
      (setq jw/x11-screen-use-all-available
            (if (and (> (length env-var) 0) (string= "yes" env-var))
                t
              nil)))

    (setq exwm-randr-workspace-monitor-plist (jw/build-workspace-monitor-plist jw/exwm-workspace-list))

    (defun jw/exwm-change-screen-hook ()
      "Execute xrandr to select and position available screens according to X11_SCREEN_* environment variables."
      (let* ((output-list (jw/xrandr-output-list))
             (available-screens (seq-intersection jw/x11-screen-list output-list))
             (available-order-screens (seq-intersection jw/x11-screen-order-list output-list))
             ;; See "--auto" in xrandr(1) and https://github.com/ch11ng/exwm/issues/529.
             (unavailable-screens (seq-difference jw/x11-screen-list output-list))
             (available-disabled-screens (seq-intersection jw/x11-screen-disabled-list output-list))
             (available-screen-modes
              (let (mode-list
                    mode screen
                    (x-screen-list jw/x11-screen-list)
                    (x-mode-list jw/x11-screen-mode-list))
                (while x-screen-list
                  (setq screen (car x-screen-list))
                  (setq x-screen-list (cdr x-screen-list))
                  (setq mode (car x-mode-list))
                  (setq x-mode-list (cdr x-mode-list))
                  (if (seq-contains available-screens screen)
                      (setq mode-list (cons mode mode-list))))
                (reverse mode-list)))
             (available-screen-rates
              (let (rate-list
                    rate screen
                    (x-screen-list jw/x11-screen-list)
                    (x-rate-list jw/x11-screen-rate-list))
                (while x-screen-list
                  (setq screen (car x-screen-list))
                  (setq x-screen-list (cdr x-screen-list))
                  (setq rate (car x-rate-list))
                  (setq x-rate-list (cdr x-rate-list))
                  (if (seq-contains available-screens screen)
                      (setq rate-list (cons rate rate-list))))
                (reverse rate-list))))
        (if available-screens
            ;; Start building xrandr command line
            (let* ((x-primary-screen
                    (if (and jw/x11-screen-preferred (seq-contains available-screens jw/x11-screen-preferred))
                        jw/x11-screen-preferred
                      (car available-screens)))
                   (screen-pos (seq-position available-screens x-primary-screen))
                   (x-primary-mode (elt available-screen-modes screen-pos))
                   (x-primary-rate (elt available-screen-rates screen-pos))
                   (xrandr-dpi-args
                    (if jw/x11-display-dpi
                        (list jw/x11-display-dpi "--dpi")))
                   (xrandr-primary-args (list x-primary-rate "--rate" x-primary-mode "--mode" "--primary" x-primary-screen "--output"))
                   screen
                   disabled-list
                   (xrandr-disabled-args
                    (progn
                      (while available-disabled-screens
                        (setq screen (car available-disabled-screens))
                        (setq available-disabled-screens (cdr available-disabled-screens))
                        (setq disabled-list (cons "--output" disabled-list))
                        (setq disabled-list (cons screen disabled-list))
                        (setq disabled-list (cons "--off" disabled-list)))
                      disabled-list))
                   (unavailable-screen-list unavailable-screens)
                   u-s-list
                   (xrandr-unavailable-screen-args
                    (progn
                      (while unavailable-screen-list
                        (setq screen (car unavailable-screen-list))
                        (setq unavailable-screen-list (cdr unavailable-screen-list))
                        (setq u-s-list (cons "--output" u-s-list))
                        (setq u-s-list (cons screen u-s-list))
                        ;; (setq u-s-list (cons "--auto" u-s-list))
                        (setq u-s-list (cons "--off" u-s-list)))
                      u-s-list))
                   (screen-list available-screens)
                   rest-list
                   (xrandr-rest-available-screen-args
                    (if jw/x11-screen-use-all-available
                         ;; Add remaining available screens, except the primary screen
                         (progn
                            (while screen-list
                               (setq screen (car screen-list))
                               (setq screen-list (cdr screen-list))
                               (if (not (string= screen x-primary-screen))
                                   (progn
                                     (setq rest-list (cons "--output" rest-list))
                                     (setq rest-list (cons screen rest-list))
                                     (setq rest-list (cons "--mode" rest-list))
                                     (setq rest-list (cons (elt available-screen-modes (seq-position available-screens screen)) rest-list))
                                     (setq rest-list (cons "--rate" rest-list))
                                     (setq rest-list (cons (elt available-screen-rates (seq-position available-screens screen)) rest-list)))))
                            rest-list)
                         ;; Disable remaining available screens, except the primary screen
                         (progn
                            (while screen-list
                               (setq screen (car screen-list))
                               (setq screen-list (cdr screen-list))
                               (if (not (string= screen x-primary-screen))
                                   (progn
                                     (setq rest-list (cons "--output" rest-list))
                                     (setq rest-list (cons screen rest-list))
                                     (setq rest-list (cons "--off" rest-list)))))
                            rest-list)))
                   (screen-order-list available-order-screens)
                   order-list
                   left-screen
                   (xrandr-screen-order-args
                    (if (and jw/x11-screen-use-all-available
                             (> (length screen-order-list) 1))
                        (progn
                           (setq left-screen (car screen-order-list))
                           (setq screen-order-list (cdr screen-order-list))
                           (while screen-order-list
                              (setq screen (car screen-order-list))
                              (setq screen-order-list (cdr screen-order-list))
                              (setq order-list (cons "--output" order-list))
                              (setq order-list (cons screen order-list))
                              (setq order-list (cons "--right-of" order-list))
                              (setq order-list (cons left-screen order-list))
                              (setq left-screen screen))
                           (reverse order-list))))
                   (xrandr-args (reverse (append xrandr-rest-available-screen-args xrandr-unavailable-screen-args
                                                 xrandr-disabled-args xrandr-primary-args xrandr-dpi-args))))
               (progn
                 (setq jw/debug-output-list output-list)
                 (setq jw/debug-xrandr-args xrandr-args)
                 (setq jw/debug-xrandr-order-args xrandr-screen-order-args)
                 (apply #'call-process
                        "/usr/bin/xrandr" nil nil nil
                        xrandr-args)
                 (if xrandr-screen-order-args
                     (apply #'call-process
                            "/usr/bin/xrandr" nil nil nil
                            xrandr-screen-order-args)))
            )
          )
        )
      )

    (add-hook 'exwm-randr-screen-change-hook 'jw/exwm-change-screen-hook)
    (exwm-randr-enable)
#+END_SRC
* exwm-config
  :PROPERTIES:
  :ID:       0f7da169-9bb9-4bad-a7b2-6c6a5db9b6ce
  :END:
#+BEGIN_SRC emacs-lisp
  (require 'ido)
  (use-package! windower)
  (require 'browse-url)
  (require 'exwm-manage)

  (defun ambrevar/call-process-to-string (program &rest args)
    "Call PROGRAM with ARGS and return output.
  See also `process-lines'."
    ;; Or equivalently:
    ;; (with-temp-buffer
    ;;   (apply 'process-file program nil t nil args)
    ;;   (buffer-string))
    (with-output-to-string
      (with-current-buffer standard-output
        (apply 'process-file program nil t nil args))))

  ;; (defun jw/xmodmap ()
  ;;   "Execute xmodmap"
  ;;   (progn
  ;;     (remove-hook 'exwm-manage-finish-hook 'jw/xmodmap)
  ;;     (ambrevar/call-process-to-string "/usr/bin/touch" "/tmp/jw_xmodmap")
  ;;     (ambrevar/call-process-to-string "/usr/bin/xmodmap" "/home/jw/.Xmodmap.exwm")))

  (defun jw/xmodmap ()
    "Execute xmodmap"
    (progn
      ;; (remove-hook 'exwm-manage-finish-hook 'jw/xmodmap)
      (ambrevar/call-process-to-string "/home/jw/bin/set_xmodmap.sh")))

  (setq browse-url-generic-program
        (or
         (executable-find (or (getenv "BROWSER") ""))
         (when (executable-find "xdg-mime")
           (let ((desktop-browser (ambrevar/call-process-to-string "xdg-mime" "query" "default" "text/html")))
             (substring desktop-browser 0 (string-match "\\.desktop" desktop-browser))))
         (executable-find browse-url-chrome-program)))

  (defun my-exwm-config-setup ()
    "My modified configuration for EXWM. Based on exwm-config.el"
    ;; Setting exwm-manage-force-tiling t has the unfortunate side effect that new floating windows
    ;; are unresponsive for a considerable time (30 seconds or so)
    ;; (setq exwm-manage-force-tiling t)
    ;; Set the initial workspace number.
    (unless (get 'exwm-workspace-number 'saved-value)
      (setq exwm-workspace-number 4))
    ;; Make class name the buffer name
    (add-hook 'exwm-update-class-hook
              (lambda ()
                (exwm-workspace-rename-buffer exwm-class-name)))
    ;; Global keybindings. 0-9 bcDfFgGhHijJkKlLmoOQrRwWå !"#¤%&/()= tab f2 backspace
    (unless (get 'exwm-input-global-keys 'saved-value)
      (setq exwm-input-global-keys
            `(
              ;; (,(kbd "s-b") . exwm-workspace-switch-to-buffer)
              (,(kbd "s-b") . helm-mini) ;; list and select buffers
              (,(kbd "s-c") . helm-resume) ;; Continue in latest helm selection buffer
              (,(kbd "s-G") . helm-locate) ;; locate file, based in Linux locate command
              (,(kbd "s-g") . mu-helm-file-search) ;; Grep search in files
              (,(kbd "s-r") . helm-run-external-command) ;; Start an application, such as google-chrome
              (,(kbd "s-W") . helm-exwm-switch-browser) ;; Switch to some browser windows
              (,(kbd "s-m") . (lambda () ;; Toggle display of mode-line and minibuffer, in an EXWM window
                                (interactive)
                                (exwm-layout-toggle-mode-line)
                                (exwm-workspace-toggle-minibuffer)))
              (,(kbd "s-i") . exwm-input-toggle-keyboard) ;; Toggle between "line-mode" and "char-mode" in an EXWM window
              ;; 's-r': Reset (to line-mode).
              (,(kbd "s-R") . exwm-reset) ;; Try to reset EXWM to a sane mode. Panic key
              ;; Interactively select, and switch to, a workspace. Only works in non EXWM windows.
              (,(kbd "s-w") . exwm-workspace-switch)
              ;; 's-å': Launch application.
              ;; (,(kbd "s-å") . (lambda (command)
              ;;              (interactive (list (read-shell-command "$ ")))
              ;;              (start-process-shell-command command nil command)))
              ;; 's-N': Switch to certain a workspace.
              ,@(mapcar (lambda (i)
                          `(,(kbd (format "s-%d" i)) .
                            (lambda ()
                              (interactive)
                              (exwm-workspace-switch-create ,i))))
                        (number-sequence 0 9))
              ;; 'S-s-N': Move window to, and switch to, a certain workspace.
              ,@(cl-mapcar (lambda (c n)
                             `(,(kbd (format "s-%c" c)) .
                               (lambda ()
                                 (interactive)
                                 (exwm-workspace-move-window ,n)
                                 (exwm-workspace-switch ,n))))
                           '(?\= ?! ?\" ?# ?¤ ?% ?& ?/ ?\( ?\))
                           (number-sequence 0 9))

              ;; Bind "s-<f2>" to "slock", a simple X display locker.
              (,(kbd "s-<f2>") . (lambda ()
                                   (interactive)
                                   (start-process "" nil "/usr/bin/slock")))
              (,(kbd "s-h") . windmove-left)  ;; Move to window to the left of current one. Uses universal arg
              (,(kbd "s-j") . windmove-down)  ;; Move to window below current one. Uses universal arg
              (,(kbd "s-k") . windmove-up)    ;; Move to window above current one. Uses universal arg
              (,(kbd "s-l") . windmove-right) ;; Move to window to the right of current one. Uses universal arg
              ;; (,(kbd "s-f") . find-file)
              (,(kbd "s-f") . helm-find-files)
              (,(kbd "s-<tab>") . windower-switch-to-last-buffer) ;; Switch to last open buffer in current window
              (,(kbd "s-s") . windower-toggle-single) ;; Toggle between multiple windows, and a single window
              (,(kbd "s-S") . windower-toggle-split)  ;; Toggle between vertical and horizontal split. Only works with exactly two windows.
              (,(kbd "s-H") . windower-swap-left)  ;; Swap current window with the window to the left
              (,(kbd "s-J") . windower-swap-below) ;; Swap current window with the window below
              (,(kbd "s-K") . windower-swap-above) ;; Swap current window with the window above
              (,(kbd "s-L") . windower-swap-right) ;; Swap current window with the window to the right
              (,(kbd "s-F") . exwm-floating-toggle-floating) ;; Toggle the current window between floating and non-floating states
              (,(kbd "s-Q") . exwm-layout-toggle-fullscreen) ;; Toggle fullscreen mode
              (,(kbd "s-D") . kill-this-buffer)
              (,(kbd "s-<backspace>") . kill-this-buffer)
              )))
    ;; Line-editing shortcuts: abBcdefFknpqsvwx
    (unless (get 'exwm-input-simulation-keys 'saved-value)
      (setq exwm-input-simulation-keys
            `((,(kbd "H-b") . ,(kbd "<left>"))
              (,(kbd "H-B") . ,(kbd "C-<left>"))
              (,(kbd "H-f") . ,(kbd "<right>"))
              (,(kbd "H-F") . ,(kbd "C-<right>"))
              (,(kbd "H-p") . ,(kbd "<up>"))
              (,(kbd "H-n") . ,(kbd "<down>"))
              (,(kbd "H-a") . ,(kbd "<home>"))
              (,(kbd "H-e") . ,(kbd "<end>"))
              ;; q and w are convenient if Caps Lock key is Hyper key
              (,(kbd "H-q") . ,(kbd "<prior>"))
              (,(kbd "H-w") . ,(kbd "<next>"))
              (,(kbd "H-d") . ,(kbd "<delete>"))
              (,(kbd "H-k") . ,(kbd "S-<end> <delete>"))
              ;; cut/paste.
              (,(kbd "H-x") . ,(kbd "C-x"))
              (,(kbd "H-c") . ,(kbd "C-c"))
              (,(kbd "H-v") . ,(kbd "C-v"))
              ;; search
              (,(kbd "H-s") . ,(kbd "C-f"))
              )))
    ;; Default is save-buffers-kill-terminal, but that may kill daemon before its finished
    (global-set-key (kbd "C-x C-c") 'save-buffers-kill-emacs)
    (add-hook 'exwm-update-title-hook 'ambrevar/exwm-rename-buffer-to-title)
    ;; Ensure that EXWM input mode is displayed in mode line
    (add-hook 'exwm-input--input-mode-change-hook
              'force-mode-line-update)
    ;; Called once, to configure X11 keyboard layout
    (add-hook 'exwm-manage-finish-hook
              'jw/xmodmap t)
    ;; Allow resizing of non-floating windows, with mouse.
    (setq window-divider-default-bottom-width 2
          window-divider-default-right-width 2)
    (window-divider-mode)
    ;; Allow switching to EXWM buffers not belonging to current workspace.
    ;; This behaviour takes some getting used to, I guess thats why its not default
    (setq exwm-layout-show-all-buffers t)
    ;; Configure Ido
    (my-exwm-config-ido)
    ;; Other configurations
    (my-exwm-config-misc))

  ;; This is copied from exwm-config.el
  (defun my-exwm-config--fix/ido-buffer-window-other-frame ()
    "Fix `ido-buffer-window-other-frame'."
    (defalias 'exwm-config-ido-buffer-window-other-frame
      (symbol-function #'ido-buffer-window-other-frame))
    (defun ido-buffer-window-other-frame (buffer)
      "This is a version redefined by EXWM.

  You can find the original one at `exwm-config-ido-buffer-window-other-frame'."
      (with-current-buffer (window-buffer (selected-window))
        (if (and (derived-mode-p 'exwm-mode)
                 exwm--floating-frame)
            ;; Switch from a floating frame.
            (with-current-buffer buffer
              (if (and (derived-mode-p 'exwm-mode)
                       exwm--floating-frame
                       (eq exwm--frame exwm-workspace--current))
                  ;; Switch to another floating frame.
                  (frame-root-window exwm--floating-frame)
                ;; Do not switch if the buffer is not on the current workspace.
                (or (get-buffer-window buffer exwm-workspace--current)
                    (selected-window))))
          (with-current-buffer buffer
            (when (derived-mode-p 'exwm-mode)
              (if (eq exwm--frame exwm-workspace--current)
                  (when exwm--floating-frame
                    ;; Switch to a floating frame on the current workspace.
                    (frame-selected-window exwm--floating-frame))
                ;; Do not switch to exwm-mode buffers on other workspace (which
                ;; won't work unless `exwm-layout-show-all-buffers' is set)
                (unless exwm-layout-show-all-buffers
                  (selected-window)))))))))

  (defun my-exwm-config-ido ()
    "Configure Ido to work with EXWM."
    ;; (ido-mode 1)
    (add-hook 'exwm-init-hook #'my-exwm-config--fix/ido-buffer-window-other-frame))

  (defun my-exwm-config-misc ()
    "Other configurations."
    ;; Make more room
    (menu-bar-mode -1)
    (tool-bar-mode -1)
    (scroll-bar-mode -1))

  ;; Rename buffer to window title.
  (defun ambrevar/exwm-rename-buffer-to-title () (exwm-workspace-rename-buffer exwm-title))

  (my-exwm-config-setup) ;; Does not start X11 or EXWM. Start should be done from commandline.
#+END_SRC
* telephone-line
  :PROPERTIES:
  :ID:       1fd4aca5-d623-49d5-9be4-54c0e96e5daf
  :END:
#+BEGIN_SRC emacs-lisp
  (use-package! telephone-line)
  (defun ambrevar/bottom-right-window-p ()
    "Determines whether the last (i.e. bottom-right) window of the
    active frame is showing the buffer in which this function is
    executed."
    (let* ((frame (selected-frame))
           (right-windows (window-at-side-list frame 'right))
           (bottom-windows (window-at-side-list frame 'bottom))
           (last-window (car (seq-intersection right-windows bottom-windows))))
      (eq (current-buffer) (window-buffer last-window))))

  (defun jw/telephone-misc-if-exwm-or-last-window ()
    "Renders the mode-line-misc-info string for display in the
    mode-line if the currently active window is the last one in the
    frame, or an exwm window.

    The idea is to not display information like the current time,
    load, battery levels on all buffers.
    And to display input mode only in exwm windows."

    (when (or (ambrevar/bottom-right-window-p)
              exwm-window-type)
      (telephone-line-raw mode-line-misc-info t)))

  (defun jw/input-mode-str ()
    "Return string representing input mode, if window is of type EXWM"
    (if exwm-window-type
        (if (eq exwm--input-mode 'line-mode)
          (format "l")
          (format "c"))
      (format "")))

  (defun jw/workspace-index ()
    "Return string representing current EXWM workspace index"
    (if (ambrevar/bottom-right-window-p)
      (format "[%s]" (exwm-workspace--position (selected-frame)))
      (format "")))

  (defun jw/format-workspace-index-and-input-mode ()
    "Return string [workspace_index]input-mode depending on exwm-window or bottom-right window"
    (format "%s%s" (jw/workspace-index) (jw/input-mode-str)))

  (defun ambrevar/telephone-line-setup ()
    (telephone-line-defsegment telephone-line-last-window-segment ()
      (jw/telephone-misc-if-exwm-or-last-window))

    ;; Display the current EXWM workspace index in the mode-line
    (telephone-line-defsegment telephone-line-exwm-workspace-index ()
      (jw/format-workspace-index-and-input-mode))

    ;; Define a highlight font for ~ important ~ information in the last
    ;; window.
    (defface special-highlight '((t (:foreground "white" :background "#5f627f"))) "")
    (add-to-list 'telephone-line-faces
                 '(highlight . (special-highlight . special-highlight)))

    (setq telephone-line-lhs
          '((nil . (telephone-line-position-segment))
            (accent . (telephone-line-buffer-segment))))

    (setq telephone-line-rhs
          '((accent . (telephone-line-major-mode-segment))
            (nil . (telephone-line-last-window-segment
                    telephone-line-exwm-workspace-index))))

    (setq telephone-line-primary-left-separator 'telephone-line-tan-left
          telephone-line-primary-right-separator 'telephone-line-tan-right
          telephone-line-secondary-left-separator 'telephone-line-tan-hollow-left
          telephone-line-secondary-right-separator 'telephone-line-tan-hollow-right)

    (telephone-line-mode 1))

  (ambrevar/telephone-line-setup)
#+END_SRC
* helm-exwm
:PROPERTIES:
:ID:       c1970c10-cefe-4040-936d-629ad5505942
:END:
#+BEGIN_SRC emacs-lisp
(use-package! helm-exwm
  :config
  (setq helm-exwm-emacs-buffers-source (helm-exwm-build-emacs-buffers-source))
  (setq helm-exwm-source (helm-exwm-build-source))
  (setq helm-mini-default-sources `(helm-exwm-emacs-buffers-source
                                    helm-exwm-source
                                    helm-source-recentf
                                    helm-source-bookmarks))
  )
#+END_SRC
* exwm-float
Turned off for now, since I force floating windows to be non floating.
BEGIN_SRC emacs-lisp
(use-package! exwm-float
  :init
  (setq exwm-float-modify-amount '(:move-slow 20 :move-fast 100 :resize 50)
        exwm-float-border '(:stationary ("navy" . 1) :moving ("maroon" . 2))
        exwm-float-position-configs
        '((:name "NW" :key "1" :title nil :x 0 :y 0 :width 0.25 :height 0.25)
          (:name "NE" :key "2" :title nil :x 0.6 :y 0 :width 0.25 :height 0.25)
          (:name "SW" :key "3" :title nil :x 0 :y -0.25 :width 0.25 :height 0.25)
          (:name "SE" :key "4" :title nil :x 0.6 :y -0.25 :width 0.25 :height 0.25)
          (:name "Center" :key "5" :title nil :x 0.25 :y 0.25 :width 0.4 :height 0.5)
          (:name "Hide" :key "h" :title nil :x 0.5 :y -1 :width 1 :height 1))
        )
  (exwm-float-setup)
  (exwm-input-set-key (kbd "C-c M-F") #'exwm-float-mode))
END_SRC
* epkg
:PROPERTIES:
:ID:       1564d129-1b92-4425-9b9f-7bc8bfe79be9
:END:
#+BEGIN_SRC emacs-lisp
(setq epkg-repository "~/epkgs/")
#+END_SRC
* Scroll in place
:PROPERTIES:
:ID:       a9a07e87-5d3c-4245-983a-82509f176c74
:END:
#+BEGIN_SRC emacs-lisp
(global-set-key [(hyper up)]
                (lambda ()
                  (interactive)
                  (let ((scroll-preserve-screen-position nil))
                    (scroll-down 1))) )
(global-set-key [(hyper down)]
                (lambda ()
                  (interactive)
                  (let ((scroll-preserve-screen-position nil))
                    (scroll-up 1))) )
#+END_SRC

* Copy paste
:PROPERTIES:
:ID:       ba586bd3-ae75-4d5e-8ca5-13bab674ffe1
:END:
#+BEGIN_SRC emacs-lisp
(setq save-interprogram-paste-before-kill t)
#+END_SRC

* Regular expressions
:PROPERTIES:
:ID:       c96ce881-ffad-4e30-a7f0-290f66d6ae3c
:END:
Use perl regular expression syntax.
#+BEGIN_SRC emacs-lisp
(pcre-mode t)
#+END_SRC

This package highlights matches and previews replacements in query replace.
#+BEGIN_SRC emacs-lisp
(use-package! visual-regexp
  :bind (;; Replace the regular query replace with the regexp query
         ;; replace provided by this package.
         ("M-%" . vr/query-replace)))
#+END_SRC

This package allows the use of other regexp engines for visual-regexp.
#+BEGIN_SRC emacs-lisp
(use-package! visual-regexp-steroids
  :after visual-regexp
  :config
  ;; Use Perl-style regular expressions by default.
  (setq vr/engine 'pcre2el))
#+END_SRC
* Swiper
:PROPERTIES:
:ID:       e76004cf-be64-440c-bb63-0479de64ee63
:END:
#+BEGIN_SRC emacs-lisp
(global-set-key (kbd "C-s") 'swiper)
#+END_SRC

* Avy
https://karthinks.com/software/avy-can-do-anything/
#+BEGIN_SRC emacs-lisp
(require 'avy)
(setq avy-all-windows t)
(setq avy-single-candidate-jump nil)
;; Avoid collision with action keys
(setq avy-keys '(?a ?s ?d ?f ?g ?h ?j ?e ?l))
(global-set-key (kbd "M-j") 'avy-goto-char-timer)
(defun avy-action-kill-whole-line (pt)
  (save-excursion
    (goto-char pt)
    (kill-whole-line))
  (select-window
   (cdr
    (ring-ref avy-ring 0)))
  t)

(setf (alist-get ?k avy-dispatch-alist) 'avy-action-kill-stay
      (alist-get ?K avy-dispatch-alist) 'avy-action-kill-whole-line)

(defun avy-action-copy-whole-line (pt)
  (save-excursion
    (goto-char pt)
    (cl-destructuring-bind (start . end)
        (bounds-of-thing-at-point 'line)
      (copy-region-as-kill start end)))
  (select-window
   (cdr
    (ring-ref avy-ring 0)))
  t)

(defun avy-action-yank-whole-line (pt)
  (avy-action-copy-whole-line pt)
  (save-excursion (yank))
  t)

(setf (alist-get ?y avy-dispatch-alist) 'avy-action-yank
      (alist-get ?w avy-dispatch-alist) 'avy-action-copy
      (alist-get ?W avy-dispatch-alist) 'avy-action-copy-whole-line
      (alist-get ?Y avy-dispatch-alist) 'avy-action-yank-whole-line)

(defun avy-action-teleport-whole-line (pt)
    (avy-action-kill-whole-line pt)
    (save-excursion (yank)) t)

(setf (alist-get ?t avy-dispatch-alist) 'avy-action-teleport
      (alist-get ?T avy-dispatch-alist) 'avy-action-teleport-whole-line)

(defun avy-action-mark-to-char (pt)
  (activate-mark)
  (goto-char pt))

(setf (alist-get ?  avy-dispatch-alist) 'avy-action-mark-to-char)

(defun avy-action-flyspell (pt)
  (save-excursion
    (goto-char pt)
    (when (require 'flyspell nil t)
      (flyspell-auto-correct-word)))
  (select-window
   (cdr (ring-ref avy-ring 0)))
  t)

;; Bind to semicolon (flyspell uses C-;)
(setf (alist-get ?\; avy-dispatch-alist) 'avy-action-flyspell)

(defun avy-action-helpful (pt)
  (save-excursion
    (goto-char pt)
    (helpful-at-point))
  (select-window
   (cdr (ring-ref avy-ring 0)))
  t)

(setf (alist-get ?H avy-dispatch-alist) 'avy-action-helpful)

(defun avy-action-embark (pt)
  (unwind-protect
      (save-excursion
        (goto-char pt)
        (embark-act))
    (select-window
     (cdr (ring-ref avy-ring 0))))
  t)

(setf (alist-get ?. avy-dispatch-alist) 'avy-action-embark)
#+END_SRC

* Embark
#+BEGIN_SRC emacs-lisp
(use-package! marginalia
  :ensure t
  :bind (("M-A" . marginalia-cycle)
         :map minibuffer-local-map
         ("M-A" . marginalia-cycle))
  :init
  ;; Must be in the :init section of use-package such that the mode gets
  ;; enabled right away. Note that this forces loading the package.
  (marginalia-mode))

(use-package! embark
  :ensure t

  :bind
  (("C-." . embark-act)         ;; pick some comfortable binding
   ("C-;" . embark-dwim)        ;; good alternative: M-.
   ("C-h B" . embark-bindings)) ;; alternative for `describe-bindings'

  :init
  ;; Optionally replace the key help with a completing-read interface
  ;; Currently is which-key-C-h-dispatch
  ;; (setq prefix-help-command #'embark-prefix-help-command)

  :config
  ;; Hide the mode line of the Embark live/completions buffers
  (add-to-list 'display-buffer-alist
               '("\\`\\*Embark Collect \\(Live\\|Completions\\)\\*"
                 nil
                 (window-parameters (mode-line-format . none))))

  (eval-when-compile
  (defmacro my/embark-ace-action (fn)
    `(defun ,(intern (concat "my/embark-ace-" (symbol-name fn))) ()
       (interactive)
       (with-demoted-errors "%s"
         (require 'ace-window)
         (let ((aw-dispatch-always t))
           (aw-switch-to-window (aw-select nil))
           (call-interactively (symbol-function ',fn)))))))

  (define-key embark-file-map     (kbd "o") (my/embark-ace-action find-file))
  (define-key embark-buffer-map   (kbd "o") (my/embark-ace-action switch-to-buffer))
  (define-key embark-bookmark-map (kbd "o") (my/embark-ace-action bookmark-jump))

  (eval-when-compile
  (defmacro my/embark-split-action (fn split-type)
    `(defun ,(intern (concat "my/embark-"
                             (symbol-name fn)
                             "-"
                             (car (last  (split-string
                                          (symbol-name split-type) "-"))))) ()
       (interactive)
       (funcall #',split-type)
       (call-interactively #',fn))))

  (define-key embark-file-map     (kbd "2") (my/embark-split-action find-file split-window-below))
  (define-key embark-buffer-map   (kbd "2") (my/embark-split-action switch-to-buffer split-window-below))
  (define-key embark-bookmark-map (kbd "2") (my/embark-split-action bookmark-jump split-window-below))

  (define-key embark-file-map     (kbd "3") (my/embark-split-action find-file split-window-right))
  (define-key embark-buffer-map   (kbd "3") (my/embark-split-action switch-to-buffer split-window-right))
  (define-key embark-bookmark-map (kbd "3") (my/embark-split-action bookmark-jump split-window-right))
  )
#+END_SRC

* Cursor
:PROPERTIES:
:ID:       bacc8d81-b02a-4a7e-8879-44e9a19b1d3e
:END:
With zenburn the cursor-color will be black for all but the initial frame unless we do some workaround.
#+BEGIN_SRC emacs-lisp
(set-cursor-color "firebrick")
(setq hcz-set-cursor-color-color "")
(setq hcz-set-cursor-color-buffer "")

(defun my-set-cursor-color ()
  "Change cursor color according to themes/init.el"
  ;; set-cursor-color is somewhat costly, so we only call it when needed:
  (let ((color "firebrick"))
    (unless (and
             (string= color hcz-set-cursor-color-color)
             (string= (buffer-name) hcz-set-cursor-color-buffer))
      (set-cursor-color (setq hcz-set-cursor-color-color color))
      (setq hcz-set-cursor-color-buffer (buffer-name)))))

(add-hook 'post-command-hook 'my-set-cursor-color)
#+END_SRC

* Handling of whitespace
** whitespace variables
:PROPERTIES:
:ID:       95bf0b35-c333-4b75-b6ab-1912022aa096
:END:
#+BEGIN_SRC emacs-lisp
(global-whitespace-mode t) ; Tell Doom that I want control over whitespace-style
(setq-default whitespace-style
              '(face
                tabs
                trailing
                empty
                )
              )
;; show unncessary whitespace that can mess up your diff
;; (add-hook 'diff-mode-hook
;;           (lambda ()
;;             (setq-local whitespace-style
;;                         '(face
;;                           tabs
;;                           tab-mark
;;                           spaces
;;                           space-mark
;;                           trailing
;;                           indentation::space
;;                           indentation::tab
;;                           newline
;;                           newline-mark))
;;             (whitespace-mode 1)))

;; (add-hook 'org-mode-hook
;;           (lambda ()
;;             (setq-local whitespace-style
;;                   (append whitespace-style '(trailing))))
;;           t) ; Add near end of hooks list of functions

(add-hook 'prog-mode-hook
          (lambda () (interactive)
            (setq show-trailing-whitespace 1)))

(add-hook 'vterm-mode-hook
          (lambda ()
            (whitespace-mode -1)
            (setq whitespace-style nil)))
#+END_SRC
** hungry-delete
   :PROPERTIES:
   :ID:       ffd0ffa4-9598-4679-8a71-a20198e2ab30
   :END:
#+BEGIN_SRC emacs-lisp
(use-package! hungry-delete
  :config
  (global-hungry-delete-mode))
#+END_SRC

* Unfill
#+BEGIN_SRC emacs-lisp
(use-package! unfill)

;; https://stackoverflow.com/questions/42595418/how-to-remove-hyphens-during-fill-paragraph
(defadvice fill-delete-newlines (before my-before-fill-delete-newlines)
  "Replace -\\n with an empty string when calling `unfill-paragraph' or `unfill-region'."
  (when (or (eq this-command 'unfill-paragraph)
            (eq this-command 'unfill-region))
    ;; (setq jw/arg0 (ad-get-arg 0))
    ;; (setq jw/arg1 (ad-get-arg 1))
    (goto-char (ad-get-arg 0))
    (while (search-forward "-\n" (ad-get-arg 1) t)
      (replace-match "")
      (ad-set-arg 1 (- (ad-get-arg 1) 2)))))

(ad-activate 'fill-delete-newlines)
#+END_SRC

* Window handling
:PROPERTIES:
:ID:       ed5f2f78-7bbb-4e11-82a4-aef8a5b0d97b
:END:
Move between windows with Shift-arrow keys
#+BEGIN_SRC emacs-lisp
(windmove-default-keybindings)
(global-set-key (kbd "<kp-4>") 'windmove-left)
(global-set-key (kbd "<kp-6>") 'windmove-right)
(global-set-key (kbd "<kp-8>") 'windmove-up)
(global-set-key (kbd "<kp-2>") 'windmove-down)
#+END_SRC
* ibuffer
:PROPERTIES:
:ID:       283daa60-cebe-4208-9eb3-86f87f66ff7c
:END:
#+BEGIN_SRC emacs-lisp
(setq ibuffer-saved-filter-groups
      '(("home"
         ("dired" (mode . dired-mode))
         ("org" (name .  ".*org$"))
;;          ("helm" (predicate string-match "Helm" mode-name))
         ("web" (or (mode .  web-mode) (mode .  js2-mode)))
         ("shell" (or (mode . eshell-mode) (mode .  shell-mode)))
         ("programming" (or (mode . python-mode) (mode . c++-mode)))
         ("emacs" (or (name . "^\\*scratch\\*$")
                      (name . "^\\*Bookmark List\\*$")
                      (name . "^\\*Compile-Log\\*$")
                      (name . "^\\*Messages\\*$")))
         ("emacs-config" (or (filename . ".emacs.d")
                             (filename . "emacs-config")))
         ("martinowen.net" (filename . "martinowen.net"))
         ("Org" (or (mode . org-mode)
                    (filename . "OrgMode")))
         ("code" (filename . "code"))
         ("Web Dev" (or (mode . html-mode)
                        (mode . css-mode)))
         ("Subversion" (name . "\*svn"))
         ("Magit" (name . "\*magit"))
         ("ERC" (mode . erc-mode))
         ("Help" (or (name . "\*Help\*")
                     (name . "\*Apropos\*")
                     (name . "\*info\*"))))))
(add-hook 'ibuffer-mode-hook
          '(lambda ()
             (ibuffer-auto-mode 1)
             (ibuffer-switch-to-saved-filter-groups "home")))
(setq ibuffer-expert t)
(setq ibuffer-show-empty-filter-groups nil)
#+END_SRC

* Python
:PROPERTIES:
:ID:       6a3e0c4b-12be-4cbb-9131-e94369f2e494
:END:
#+BEGIN_SRC emacs-lisp
(setq python-shell-interpreter "python3")
#+END_SRC
* Thingatpt-plus
:PROPERTIES:
:ID:       df3657ef-cc26-4e6e-8b12-7cfad1b03c2c
:END:
#+BEGIN_SRC emacs-lisp
(use-package! thingatpt+)
#+END_SRC

* Hide-comnt
:PROPERTIES:
:ID:       e2388ad7-3f34-46b9-8adf-47bac898eb68
:END:
#+BEGIN_SRC emacs-lisp
(use-package! hide-comnt)
#+END_SRC

* Thing-cmds
:PROPERTIES:
:ID:       76e24063-31ea-402a-89d0-4990a32ba8aa
:END:
#+BEGIN_SRC emacs-lisp
  (use-package! thing-cmds)
#+END_SRC
* Hexrgb
:PROPERTIES:
:ID:       78ea1431-f4fc-4ac3-aaf4-d044b940cdcb
:END:
#+BEGIN_SRC emacs-lisp
(use-package! hexrgb)
#+END_SRC
* Palette
:PROPERTIES:
:ID:       b0e62fac-1624-4a6b-83cf-aedb8981981b
:END:
#+BEGIN_SRC emacs-lisp
  (use-package! palette)
#+END_SRC
* Facemenu-plus
:PROPERTIES:
:ID:       f62a3f6f-2cbc-4299-baf0-07edc3e36a97
:END:
#+BEGIN_SRC emacs-lisp
  (use-package! facemenu+)
#+END_SRC
* Highlight
:PROPERTIES:
:ID:       e28d708e-0e64-4d75-82f2-a6a298d5dc56
:END:
#+BEGIN_SRC emacs-lisp
  (use-package! highlight)
#+END_SRC
* Mouse3
:PROPERTIES:
:ID:       0bcf11b6-277a-4076-8366-7ef0788fa2c9
:END:
#+BEGIN_SRC emacs-lisp
  (use-package! mouse3)
#+END_SRC
* Dired
** Settings
:PROPERTIES:
:ID:       642ede15-57ff-46cf-95ad-7bcf62a41839
:END:
#+BEGIN_SRC emacs-lisp
(setq dired-clean-up-buffers-too nil) ; Avoid pesky questions about deleting orphan buffers
(defconst my-dired-media-files-extensions
 '("mp3" "mp4" "MP3" "MP4" "avi" "mpg" "flv" "ogg" "wmv" "mkv" "mov" "wma")
  "Media file extensions that should launch in VLC.
Also used for highlighting.")
#+END_SRC
** Filter
:PROPERTIES:
:ID:       d12c758c-c200-4b3c-b582-a40fa1d07b73
:END:
#+BEGIN_SRC emacs-lisp
  (bind-keys :map dired-mode-map
             ("ö" . dired-filter-map)
             ("ä" . dired-filter-mark-map))
  (use-package! dired-filter
    :config
    (setq dired-filter-group-saved-groups
       (make-list 1 '("default"
                      ("Epub"
                       (extension . "epub"))
                      ("PDF"
                       (extension . "pdf"))
                      ("LaTeX"
                       (extension "tex" "bib"))
                      ("Org"
                       (extension . "org"))
                      ("Archives"
                       (extension "zip" "rar" "gz" "bz2" "tar")))))
  )
  #+END_SRC
** Narrow
:PROPERTIES:
:ID:       5814ac05-2b1a-4b97-b813-4476602351bb
:END:
Narrow dired to match filter
#+BEGIN_SRC emacs-lisp
(use-package! dired-narrow
  :commands dired-narrow
  :init
  (map! :map dired-mode-map
        :desc "Live filtering" "å" #'dired-narrow))
#+END_SRC
** Launch
:PROPERTIES:
:ID:       a20d1812-e114-4272-b688-8af503934f08
:END:
Launch application associated with file
#+BEGIN_SRC emacs-lisp
(use-package! dired-launch)
(dired-launch-enable)
#+END_SRC
** dired-ranger
   :PROPERTIES:
   :ID:       893b721b-b1be-4ee0-8a1a-5cecf64432c2
   :END:
#+BEGIN_SRC emacs-lisp
  (use-package! dired-ranger
    :config
    (setq dired-ranger-bookmark-LRU ?l)
    ;; (bind-keys :map dired-mode-map
    ;;            :prefix "c"
    ;;            :prefix-map dired-ranger-map
    ;;            :prefix-docstring "Map for ranger operations."
    ;;   ("c" . dired-ranger-copy)
    ;;   ("p" . dired-ranger-paste)
    ;;   ("m" . dired-ranger-move))
    :bind (:map dired-mode-map
                ("W" . dired-ranger-copy)
                ("X" . dired-ranger-move)
                ("Y" . dired-ranger-paste)
                ("'" . dired-ranger-bookmark)
                ("l" . dired-ranger-bookmark-visit))
  )
(ranger-override-dired-mode -1)
#+END_SRC
** Init
:PROPERTIES:
:ID:       392b13af-61d4-4495-803f-a9e11f493184
:END:
#+BEGIN_SRC emacs-lisp
(defun my-dired-init ()
  "Bunch of stuff to run for dired, either immediately or when it's loaded."
  (bind-keys :map dired-mode-map
    ("<delete>" . dired-unmark-backward)
    ("<backspace>" . dired-up-directory))

  (dired-filter-mode t)
  (dired-filter-group-mode t)
  ;; (dired-collapse-mode 1)
  (visual-line-mode -1)
  (toggle-truncate-lines 1))
(add-hook 'dired-mode-hook 'my-dired-init)
#+END_SRC
* Dired plus
:PROPERTIES:
:ID:       08d77230-4abb-4dce-9ec6-054e8d20f90c
:END:
#+BEGIN_SRC emacs-lisp
  (use-package! dired+
    :config
    (setq diredp-image-preview-in-tooltip 300))
#+END_SRC

* Bookmarks
:PROPERTIES:
:ID:       e4d07c0e-35c6-4736-85ed-319ecc744bd6
:END:
#+BEGIN_SRC emacs-lisp
  (use-package! bookmark+)
#+END_SRC

* w3m
** w3m proper
:PROPERTIES:
:ID:       edbe3fc4-4052-4ad6-9228-79f673adafbd
:END:
Text based internet browser
#+BEGIN_SRC emacs-lisp
  (use-package! w3m
    :config
    (setq w3m-key-binding 'info)
     (define-key w3m-mode-map [up] 'previous-line)
     (define-key w3m-mode-map [down] 'next-line)
     (define-key w3m-mode-map [left] 'backward-char)
     (define-key w3m-mode-map [right] 'forward-char)
    (setq w3m-default-display-inline-images t)
    (setq w3m-make-new-session t)
    (setq w3m-use-cookies t)
    (setq w3m-default-save-directory "~/Downloads/")
    (add-hook 'w3m-display-hook
            (lambda (url)
              (rename-buffer
               (format "*w3m: %s*"
                       (or w3m-current-title w3m-current-url)) t)))
    (defun wicked/w3m-open-current-page-in-chrome ()
      "Open the current URL in Google Chrome."
      (interactive)
      (browse-url-chrome w3m-current-url)) ;; (1)

    (defun wicked/w3m-open-link-or-image-in-chrome ()
      "Open the current link or image in Chrome."
      (interactive)
      (browse-url-chrome (or (w3m-anchor) ;; (2)
                             (w3m-image)))) ;; (3)
    (define-key w3m-mode-map (kbd "f") 'wicked/w3m-open-current-page-in-chrome)
    (define-key w3m-mode-map (kbd "F") 'wicked/w3m-open-link-or-image-in-chrome)
  )
#+END_SRC
** w3m search engines
:PROPERTIES:
:ID:       09757828-6e59-49b5-9e9e-63620ec8f776
:END:
w3m-search search engines
#+BEGIN_SRC emacs-lisp
(eval-after-load "w3m-search"
  '(progn
    (add-to-list 'w3m-search-engine-alist
                 '("archwiki"
                   "https://wiki.archlinux.org/index.php?search=%s"
                   nil))
    (add-to-list 'w3m-search-engine-alist
                 '("ask"
                   "https://www.ask.com/web?q=%s"
                   nil))
    (add-to-list 'w3m-search-engine-alist
                 '("bbcnews"
                   "http://search.bbc.co.uk/search?scope=all&tab=ns&q=%s"
                   nil))
    (add-to-list 'w3m-search-engine-alist
                 '("cia"
                   "https://www.cia.gov/search?q=%s&site=CIA&client=CIA&proxystylesheet=CIA&output=xml_no_dtd&myAction=%2Fsearch&submitMethod=get"
                   nil))
    (add-to-list 'w3m-search-engine-alist
                 '("cpan"
                   "https://metacpan.org/search?q=%s"
                   nil))
    (add-to-list 'w3m-search-engine-alist
                 '("debian-wiki"
                   "https://wiki.debian.org/FindPage?action=fullsearch&titlesearch=0&value=%s&submit=Search+Text"
                   nil))
    (add-to-list 'w3m-search-engine-alist
                 '("loc"
                   "http://www.loc.gov/search/?q=%s"
                   nil))
    (add-to-list 'w3m-search-engine-alist
                 '("py2doc"
                   "http://docs.python.org/2/search.html?q=%s"
                   nil))
    (add-to-list 'w3m-search-engine-alist
                 '("py3doc"
                   "http://docs.python.org/3/search.html?q=%s"
                   nil))
    (add-to-list 'w3m-search-engine-alist
                 '("reddit"
                   "http://www.reddit.com/search?q=%s"
                   nil))
   )
)
#+END_SRC
** ace-link
:PROPERTIES:
:ID:       9304220d-e768-4ee5-9dba-98691ebb255e
:END:
Use ace-link
#+BEGIN_SRC emacs-lisp
  (use-package! ace-link
    :config
    (ace-link-setup-default))
#+END_SRC
** Follow links in w3m
:PROPERTIES:
:ID:       b045ca5b-93db-49ec-aa5e-aabcbd2484ce
:END:
Follow links in w3m. For keybindings see [[*launcher map]]
#+BEGIN_SRC emacs-lisp
  (setq browse-url-mosaic-program nil)
  (setq browse-url-browser-function 'w3m-browse-url
        browse-url-new-window-flag t)
  (autoload 'w3m-browse-url "w3m" "Ask a WWW browser to show a URL." t)
  (autoload 'browse-url-interactive-arg "browse-url")
#+END_SRC
** helm-w3m
   :PROPERTIES:
   :ID:       bd7f3c36-cb10-47fb-9eea-02fd8fd049bf
   :END:
#+BEGIN_SRC emacs-lisp
  (use-package! helm-w3m)
#+END_SRC

* url-decode
#+BEGIN_SRC emacs-lisp
(defun xah-html-decode-percent-encoded-url ()
  "Decode percent encoded URL of current line or selection.

Example:
 %28D%C3%BCrer%29
becomes
 (Dürer)

Example:
 %E6%96%87%E6%9C%AC%E7%BC%96%E8%BE%91%E5%99%A8
becomes
 文本编辑器

URL `http://xahlee.info/emacs/emacs/emacs_url_percent_decode.html'
Version 2018-10-26"
  (interactive)
  (let ( $p1 $p2 $input-str $newStr)
    (if (use-region-p)
        (setq $p1 (region-beginning) $p2 (region-end))
      (setq $p1 (line-beginning-position) $p2 (line-end-position)))
    (setq $input-str (buffer-substring-no-properties $p1 $p2))
    (require 'url-util)
    (setq $newStr (url-unhex-string $input-str))
    (if (string-equal $newStr $input-str)
        (progn (message "no change" ))
      (progn
        (delete-region $p1 $p2)
        (insert (decode-coding-string $newStr 'utf-8))))))

(defun jw/clean-org-protocol-l-result ()
  "Decode percent encoded result from org-protocol, capture key l. Delete text before url, add newline before title."
  (interactive)
  (save-excursion
    (mark-paragraph)
    (xah-html-decode-percent-encoded-url)
    (goto-char (region-beginning))
    (if (re-search-forward "org-protocol.*url=" nil t)
        (replace-match "" nil nil))
    (if (search-forward "&title=" nil t)
        (replace-match "\ntitle=" nil nil))
    (if (search-forward "&body=" nil t)
        (replace-match "\nbody=" nil nil))
    )
  )

(defun tina/test-finalize ()
  (let ((key  (plist-get org-capture-plist :key))
        (desc (plist-get org-capture-plist :description)))
    (if org-note-abort
        (message "Template with key %s and description “%s” aborted" key desc)
      (message "Template with key %s and description “%s” run successfully" key desc))))

(defun jw/hook-clean-org-protocol-l-result ()
  "Wrapper around jw/clean-org-protocol-l-result, for add to hook."
  (when (and (not org-note-abort)
             (equal (plist-get org-capture-plist :key) "l"))
    (jw/clean-org-protocol-l-result))
  )

;; https://emacs.stackexchange.com/questions/45270/in-org-mode-how-can-i-make-a-post-capture-hook-run-only-for-certain-capture-tem
;; (after! org (add-hook 'org-capture-after-finalize-hook 'tina/test-finalize))
(after! org
  (add-hook 'org-capture-prepare-finalize-hook 'jw/hook-clean-org-protocol-l-result))
#+END_SRC

* org-protocol-capture-html
#+BEGIN_SRC emacs-lisp
(use-package! org-protocol-capture-html)
;; (require 'org-protocol-capture-html)
#+END_SRC

* launcher map
:PROPERTIES:
:ID:       34f0cfed-5dfd-4c4d-95d6-d403e1dadcfd
:END:
#+BEGIN_SRC emacs-lisp
(define-prefix-command 'launcher-map)
(define-key launcher-map "c" #'link-hint-copy-link)
(define-key launcher-map "C" #'org-capture)
(define-key launcher-map "d" #'helpful-at-point)
(define-key launcher-map "e" #'er/expand-region)
(define-key launcher-map "E" #'er/contract-region)
(define-key launcher-map "f" #'find-dired)
(define-key launcher-map "g" #'w3m-search)
(define-key launcher-map "j" #'org-journal-new-entry)
(define-key launcher-map "l" #'browse-url-at-point)
(define-key launcher-map "o" #'link-hint-open-link)
(define-key launcher-map "t" #'proced) ; top
;;(define-key launcher-map "u" #'my/copy-id-to-clipboard)
(define-key launcher-map "w" #'w3m-goto-url)
(global-set-key (kbd "H-l") 'launcher-map)
#+END_SRC

* elfeed
** elfeed proper
:PROPERTIES:
:ID:       5bf22928-79d7-4418-8d70-2d7277d51751
:END:
#+BEGIN_SRC emacs-lisp
  ;;shortcut functions
  (defun bjm/elfeed-show-all ()
    (interactive)
    (bookmark-maybe-load-default-file)
    (bookmark-jump "elfeed-all"))
  (defun bjm/elfeed-show-emacs ()
    (interactive)
    (bookmark-maybe-load-default-file)
    (bookmark-jump "elfeed-emacs"))
  (defun bjm/elfeed-show-daily ()
    (interactive)
    (bookmark-maybe-load-default-file)
    (bookmark-jump "elfeed-daily"))
  ;;functions to support syncing .elfeed between machines
  ;;makes sure elfeed reads index from disk before launching
  (defun bjm/elfeed-load-db-and-open ()
    "Wrapper to load the elfeed db from disk before opening"
    (interactive)
    (elfeed-db-load)
    (elfeed)
    (elfeed-search-update--force))

  ;;write to disk when quiting
  (defun bjm/elfeed-save-db-and-bury ()
    "Wrapper to save the elfeed db to disk before burying buffer"
    (interactive)
    (elfeed-db-save)
    (quit-window))
  (defun mz/elfeed-browse-url (&optional use-generic-p)
      "Visit the current entry in your browser using `browse-url'.
    If there is a prefix argument, visit the current entry in the
    browser defined by `browse-url-generic-program'."
      (interactive "P")
      (let ((entries (elfeed-search-selected)))
        (cl-loop for entry in entries
                 do (if use-generic-p
                        (browse-url-chrome (elfeed-entry-link entry))
                      (browse-url (elfeed-entry-link entry))))
        (mapc #'elfeed-search-update-entry entries)
        (unless (or elfeed-search-remain-on-entry (use-region-p))
        ;;(forward-line)
  )))
  (defun elfeed-mark-all-as-read ()
    (interactive)
    (mark-whole-buffer)
    (elfeed-search-untag-all-unread))
  (use-package! elfeed
    :bind (:map elfeed-search-mode-map
               ("A" . bjm/elfeed-show-all)
               ("E" . bjm/elfeed-show-emacs)
               ("D" . bjm/elfeed-show-daily)
               ("b" . mz/elfeed-browse-url)
               ("B" . elfeed-search-browse-url)
               ("j" . mz/make-and-run-elfeed-hydra)
               ("m" . elfeed-toggle-star)
               ("q" . bjm/elfeed-save-db-and-bury))
    :config
    (defalias 'elfeed-toggle-star
       (elfeed-expose #'elfeed-search-toggle-all 'star))
  )
#+END_SRC
** elfeed-org
:PROPERTIES:
:ID:       4dc75ae1-0956-44c3-8faf-b8352ac076fd
:END:
#+BEGIN_SRC emacs-lisp
  ;; Load elfeed-org
  (use-package! elfeed-org
    :init
    (setq rmh-elfeed-org-files (list "~/.doom.d/elfeed.org"))
    :config
    (elfeed-org))
  (defun z/hasCap (s) ""
    (let ((case-fold-search nil))
    (string-match-p "[[:upper:]]" s)))
  (defun z/get-hydra-option-key (s)
    "returns single upper case letter (converted to lower) or first"
    (interactive)
    (let ( (loc (z/hasCap s)))
    (if loc
      (downcase (substring s loc (+ loc 1)))
      (substring s 0 1)
  )))
  (defun mz/make-elfeed-cats (tags)
    "Returns a list of lists. Each one is line for the hydra configuratio in the form
    (c function hint)"
    (interactive)
    (mapcar (lambda (tag)
      (let* (
             (tagstring (symbol-name tag))
             (c (z/get-hydra-option-key tagstring)))
        (list c (append '(elfeed-search-set-filter) (list (format "@6-months-ago +%s" tagstring) ))tagstring  )))
      tags))
  (defmacro mz/make-elfeed-hydra ()
    `(defhydra mz/hydra-elfeed ()
      "filter"
      ,@(mz/make-elfeed-cats (elfeed-db-get-all-tags))
      ("*" (elfeed-search-set-filter "@6-months-ago +star") "Starred")
      ("M" elfeed-toggle-star "Mark")
      ("A" (elfeed-search-set-filter "@6-months-ago") "All")
      ("T" (elfeed-search-set-filter "@1-day-ago") "Today")
      ("Q" bjm/elfeed-save-db-and-bury "Quit Elfeed" :color blue)
      ("q" nil "quit" :color blue)
  ))
  (defun mz/make-and-run-elfeed-hydra ()
    ""
    (interactive)
    (mz/make-elfeed-hydra)
    (mz/hydra-elfeed/body))
  (defun my-elfeed-tag-sort (a b)
    (let* ((a-tags (format "%s" (elfeed-entry-tags a)))
           (b-tags (format "%s" (elfeed-entry-tags b))))
      (if (string= a-tags b-tags)
          (< (elfeed-entry-date b) (elfeed-entry-date a)))
      (string< a-tags b-tags)))
  (setf elfeed-search-sort-function #'my-elfeed-tag-sort)
#+END_SRC

* novel
:PROPERTIES:
:ID:       05e8da14-d5e3-4d94-843a-aba8a75d373a
:END:
#+BEGIN_SRC emacs-lisp
(use-package! nov
  :init
  (push '("\\.epub\\'" . nov-mode) auto-mode-alist)
  :bind
  (:map nov-mode-map
        ("<home>" . move-beginning-of-line)
        ("<end>" . move-end-of-line)
        ))
#+END_SRC

* calibredb
:PROPERTIES:
:ID:       c7ecb172-a8f4-491f-8e9b-6df0a3f86959
:END:
#+BEGIN_SRC emacs-lisp
  ;; (defun my-window-displaying-calibredb-entry-p (window)
  ;;   (equal (with-current-buffer (window-buffer window) major-mode)
  ;;          'calibredb-show))

  ;; (defun my-position-calibredb-entry-buffer (buffer alist)
  ;;   (let ((agenda-window (car (cl-remove-if-not #'my-window-displaying-calibredb-entry-p (window-list)))))
  ;;     (when agenda-window
  ;;       (set-window-buffer agenda-window  buffer)
  ;;       agenda-window)))

  (use-package! calibredb
    :config
    (setq sql-sqlite-program "/usr/bin/sqlite3")
    (setq calibredb-program "/usr/bin/calibredb")
    (setq calibredb-root-dir (expand-file-name "~/calibre_library"))
    (setq calibredb-db-dir (concat calibredb-root-dir "/metadata.db"))
    (setq calibredb-library-alist '(("~/calibre_library")))
    (setq calibredb-date-width 0)
    (setq calibredb-download-dir (expand-file-name "~/Downloads"))
    (setq calibredb-library-alist '(("/home/jw/calibre_library")
                                    ("https://bookserver.archive.org/catalog/")
                                    ("http://arxiv.maplepop.com/catalog/")
                                    ("https://m.gutenberg.org/ebooks.opds/")
                                    ))

    ;; (add-to-list 'display-buffer-alist (cons "\\*calibredb-entry\\*" (cons #'my-position-calibredb-entry-buffer nil)))
    )
#+END_SRC

* good-scroll
:PROPERTIES:
:ID:       edf93ee6-0e81-4e8a-a933-9969c26201d1
:END:
#+BEGIN_SRC emacs-lisp
  (use-package! good-scroll
    :config
    (good-scroll-mode 1))
#+END_SRC
* fish-completion
:PROPERTIES:
:ID:       3937ebe5-daf8-440c-b717-343a1d8bde99
:END:
#+BEGIN_SRC emacs-lisp
(when (and (executable-find "fish")
           (require 'fish-completion nil t))
  (global-fish-completion-mode))
#+END_SRC
* mixed-pitch
:PROPERTIES:
:ID:       63900c51-386b-4b96-a5fc-1673097242d0
:END:
#+BEGIN_SRC emacs-lisp
(use-package! mixed-pitch)
#+END_SRC

* smartparens
:PROPERTIES:
:ID:       d4c48025-9aaa-4b27-b0d7-6d47baac03cf
:END:
#+BEGIN_SRC emacs-lisp
(use-package! smartparens)
#+END_SRC

* hyperbole
:PROPERTIES:
:ID:       2f2277b1-fae3-4dad-bd53-aae4dd0b4a66
:END:
#+BEGIN_SRC emacs-lisp
  (use-package! hyperbole
    :config
    ;; (require 'hyperbole)
    ;; (hyperbole-mode 1)
    (setq hsys-org-enable-smart-keys t)
    (global-set-key (kbd "H-<return>") 'hkey-either)
    (global-set-key (kbd "S-s-<return>") 'assist-key)
    (global-set-key (kbd "<mouse-9>") 'action-mouse-key-emacs)
    (global-set-key (kbd "<double-mouse-9>") 'action-mouse-key-emacs)
    (global-set-key (kbd "<triple-mouse-9>") 'action-mouse-key-emacs)
    (global-set-key (kbd "<down-mouse-9>") 'action-key-depress-emacs)
    (global-set-key (kbd "<drag-mouse-9>") 'action-mouse-key-emacs)
    (global-set-key (kbd "<left-fringe> <mouse-9>") 'action-mouse-key-emacs)
    (global-set-key (kbd "<left-fringe> <down-mouse-9>") 'action-key-depress-emacs)
    (global-set-key (kbd "<left-fringe> <drag-mouse-9>") 'action-mouse-key-emacs)
    (global-set-key (kbd "<right-fringe> <mouse-9>") 'action-mouse-key-emacs)
    (global-set-key (kbd "<right-fringe> <down-mouse-9>") 'action-key-depress-emacs)
    (global-set-key (kbd "<right-fringe> <drag-mouse-9>") 'action-mouse-key-emacs)
    (global-set-key (kbd "<vertical-line> <mouse-9>") 'action-mouse-key-emacs)
    (global-set-key (kbd "<vertical-line> <down-mouse-9>") 'action-key-depress-emacs)
    (global-set-key (kbd "<vertical-line> <drag-mouse-9>") 'action-mouse-key-emacs)
    (global-set-key (kbd "<mode-line> <mouse-9>") 'action-mouse-key-emacs)
    (global-set-key (kbd "<mode-line> <down-mouse-9>") 'action-key-depress-emacs)
    (global-set-key (kbd "<mode-line> <drag-mouse-9>") 'action-mouse-key-emacs)
    (global-set-key (kbd "<header-line> <mouse-9>") 'action-mouse-key-emacs)
    (global-set-key (kbd "<header-line> <down-mouse-9>") 'action-key-depress-emacs)
    (global-set-key (kbd "<header-line> <drag-mouse-9>") 'action-mouse-key-emacs)
    (hkey-ace-window-setup)
    ;; (global-set-key (kbd "s-o") 'hkey-operate)
    )
#+END_SRC
* Hydra
** hydra-helm
:PROPERTIES:
:ID:       6b0ec6a8-4ee3-4381-aaf8-4d927019617e
:END:
#+BEGIN_SRC emacs-lisp
(defhydra hydra-helm (:hint nil :color pink)
        "
                                                                          ╭──────┐
   Navigation   Other  Sources     Mark             Do             Help   │ Helm │
  ╭───────────────────────────────────────────────────────────────────────┴──────╯
        ^_k_^         _K_       _p_   [_m_] mark         [_v_] view         [_H_] helm help
        ^^↑^^         ^↑^       ^↑^   [_t_] toggle all   [_d_] delete       [_s_] source help
    _h_ ←   → _l_     _c_       ^ ^   [_u_] unmark all   [_f_] follow: %(helm-attr 'follow)
        ^^↓^^         ^↓^       ^↓^    ^ ^               [_y_] yank selection
        ^_j_^         _J_       _n_    ^ ^               [_w_] toggle windows
  --------------------------------------------------------------------------------
        "
        ("<tab>" helm-keyboard-quit "back" :exit t)
        ("<escape>" nil "quit")
        ("\\" (insert "\\") "\\" :color blue)
        ("h" helm-beginning-of-buffer)
        ("j" helm-next-line)
        ("k" helm-previous-line)
        ("l" helm-end-of-buffer)
        ("g" helm-beginning-of-buffer)
        ("G" helm-end-of-buffer)
        ("n" helm-next-source)
        ("p" helm-previous-source)
        ("K" helm-scroll-other-window-down)
        ("J" helm-scroll-other-window)
        ("c" helm-recenter-top-bottom-other-window)
        ("m" helm-toggle-visible-mark)
        ("t" helm-toggle-all-marks)
        ("u" helm-unmark-all)
        ("H" helm-help)
        ("s" helm-buffer-help)
        ("v" helm-execute-persistent-action)
        ("d" helm-persistent-delete-marked)
        ("y" helm-yank-selection)
        ("w" helm-toggle-resplit-and-swap-windows)
        ("f" helm-follow-mode))

(define-key helm-map (kbd "H-o") 'hydra-helm/body)
#+END_SRC
** hydra-projectile
   :PROPERTIES:
   :ID:       2e013630-fe3e-44d0-9e57-8d65e03f18d5
   :END:
#+BEGIN_SRC emacs-lisp
(defhydra hydra-projectile-other-window (:color teal)
  "projectile-other-window"
  ("f"  projectile-find-file-other-window        "file")
  ("g"  projectile-find-file-dwim-other-window   "file dwim")
  ("d"  projectile-find-dir-other-window         "dir")
  ("b"  projectile-switch-to-buffer-other-window "buffer")
  ("q"  nil                                      "cancel" :color blue))

;; (use-package ggtags
;;   :config
;;   (add-hook 'c-mode-common-hook
;;             (lambda ()
;;               (when (derived-mode-p 'c-mode 'c++-mode 'java-mode)
;;                 (ggtags-mode 1))))
;;   )

(defhydra hydra-projectile (:color teal
                            :hint nil)
  "
     PROJECTILE: %(projectile-project-root)

     Find File            Search/Tags          Buffers                Cache
------------------------------------------------------------------------------------------
_s-f_: file            _a_: ag                _i_: Ibuffer           _c_: cache clear
 _ff_: file dwim       _g_: update gtags      _b_: switch to buffer  _x_: remove known project
 _fd_: file curr dir   _o_: multi-occur     _s-k_: Kill all buffers  _X_: cleanup non-existing
  _r_: recent file                                               ^^^^_z_: cache current
  _d_: dir

"
  ("a"   projectile-ag)
  ("b"   projectile-switch-to-buffer)
  ("c"   projectile-invalidate-cache)
  ("d"   projectile-find-dir)
  ("s-f" projectile-find-file)
  ("ff"  projectile-find-file-dwim)
  ("fd"  projectile-find-file-in-directory)
  ("g"   ggtags-update-tags)
  ("s-g" ggtags-update-tags)
  ("i"   projectile-ibuffer)
  ("K"   projectile-kill-buffers)
  ("s-k" projectile-kill-buffers)
  ("m"   projectile-multi-occur)
  ("o"   projectile-multi-occur)
  ("s-p" projectile-switch-project "switch project")
  ("p"   projectile-switch-project)
  ("s"   projectile-switch-project)
  ("r"   projectile-recentf)
  ("x"   projectile-remove-known-project)
  ("X"   projectile-cleanup-known-projects)
  ("z"   projectile-cache-current-file)
  ("`"   hydra-projectile-other-window/body "other window")
  ("q"   nil "cancel" :color blue))
#+END_SRC

* keyboard macros
:PROPERTIES:
:ID:       482c830d-910a-4148-81d1-957dca7eb66b
:END:
#+BEGIN_SRC emacs-lisp
;; Change "Jane Joplin & John B Doe_" -> "Jane Joplin_ & Doe, John B"
(fset 'jw/swap_author
      (kmacro-lambda-form [?\M-b left ?\M-d ?\M-x ?s ?e ?a ?r ?c ?h ?- ?b ?a ?c ?k ?w ?a ?r ?d ?s backspace return ?& return ?\C-f ?\C-y ?, ?\M-b ?\M-b ?\M-f] 0 "%d"))

;; Replace "," with " &"
(fset 'jw/comma_to_ampersand
      (kmacro-lambda-form [?\M-x ?r ?e ?p ?l ?a ?c ?e ?- ?s ?t ?r ?i ?n ?g return ?, return ?  ?& return] 0 "%d"))
#+END_SRC
* session
:PROPERTIES:
:ID:       1a73babb-8d06-4aec-92c6-9bc577269aeb
:END:
#+BEGIN_SRC emacs-lisp
(require 'session)
(add-hook 'after-init-hook 'session-initialize)
;; (setq session-use-package t nil (session))
;; session will be save if a buffer is save to a file.
(add-hook 'after-save-hook #'session-save-session)
#+END_SRC
* zoxide
:PROPERTIES:
:ID:       0e8c9114-8740-4818-9860-f8951bb19ca9
:END:
#+BEGIN_SRC emacs-lisp
(use-package! zoxide)
#+END_SRC
* hledger-mode
#+BEGIN_SRC emacs-lisp
(use-package! hledger-mode
  :config
  ;; To open files with .journal extension in hledger-mode
  (add-to-list 'auto-mode-alist '("\\.journal\\'" . hledger-mode))
  ;; Provide the path to you journal file.
  ;; The default location is too opinionated.
  (setq hledger-jfile "/home/jw/Dokument/hledger/test/test1.journal")
  )

;; Out of sync with hledger
;; (use-package! flycheck-hledger
;;   :after (flycheck hledger-mode)
;;   :demand t)

(load "~/.doom.d/ob-hledger")
(require 'ob-hledger)
#+END_SRC

* cc-mode
#+BEGIN_SRC emacs-lisp
(set-eglot-client! 'cc-mode '("clangd" "-j=3" "--clang-tidy"))
#+END_SRC

* engine-mode
engine-mode is a global minor mode for Emacs. It enables you to easily define search engines, bind them to keybindings, and query them from the comfort of your editor.
#+BEGIN_SRC emacs-lisp
(require 'engine-mode)
(engine-mode t)
#+END_SRC

* Common lisp
Enabled in init.el: common-lisp
#+BEGIN_SRC emacs-lisp
(setq common-lisp-hyperspec-root
;; “http://www.lispworks.com/reference/HyperSpec/&#8221;)
"file:///home/jw/lisp/HyperSpec/")
;; (setq browse-url-browser-function ‘eww-browse-url)
(setq common-lisp-hyperspec-symbol-table "/home/jw/lisp/HyperSpec/Data/Map_Sym.txt")
;; block images in EWW browser
;; (setq-default shr-inhibit-images t)
#+END_SRC

* arxiv-mode
#+BEGIN_SRC emacs-lisp
(use-package! arxiv-mode
  :ensure t
  )
#+END_SRC

* pdftottext
#+BEGIN_SRC emacs-lisp
(use-package! pdftotext
  ;; For prettyness
  ;; (add-hook 'pdftotext-mode-hook #'spell-fu-mode-disable)
  ;; (add-hook 'pdftotext-mode-hook (lambda () (page-break-lines-mode 1)))
  ;; I have no idea why this is needed
  ;; (map! :map pdftotext-mode-map
  ;;       "<mouse-4>" (cmd! (scroll-down mouse-wheel-scroll-amount-horizontal))
  ;;       "<mouse-5>" (cmd! (scroll-up mouse-wheel-scroll-amount-horizontal)))
  )

(defun pdftotext-enable ()
  "Enable pdftotext-mode."
  (interactive)
  (after! pdf-tools (pdftotext-install))
  )

(defun pdftotext-disable ()
  "Disable pdftotext-mode."
  (interactive)
  (after! pdf-tools (progn
                      (pdftotext-uninstall)
                      (add-to-list 'auto-mode-alist pdf-tools-auto-mode-alist-entry)
                      (add-to-list 'magic-mode-alist pdf-tools-magic-mode-alist-entry)
                      )
    )
  )

 #+END_SRC

* xah-math-input
#+BEGIN_SRC emacs-lisp
(use-package! xah-math-input
  :config
(xah-math-input--add-to-hash
 '(
   ["zws" "​"]
   ))
  )
#+END_SRC
* emacs-with-nyxt
#+BEGIN_SRC emacs-lisp
;; (require 'org)
(require 's)
(require 'sly)

(defcustom cl-ide 'sly
  "What IDE to use to evaluate Common Lisp.
Defaults to Sly because it has better integration with Nyxt."
  :options (list 'sly 'slime))

(defvar emacs-with-nyxt-delay
  0.1
  "Delay to wait for `cl-ide' commands to reach Nyxt.")

(setq slime-protocol-version 'ignore)

(defun emacs-with-nyxt-connected-p ()
  "Is `cl-ide' connected to nyxt."
  (cond
   ((eq cl-ide 'slime) (slime-connected-p))
   ((eq cl-ide 'sly) (sly-connected-p)))) ;; TODO this should check it
                                          ;; is connected to Nyxt and
                                          ;; not just to cl-ide
                                          ;; session

(defun emacs-with-nyxt--connect (host port)
  "Connect `cl-ide' to HOST and PORT."
  (cond
   ((eq cl-ide 'slime) (slime-connect host port))
   ((eq cl-ide 'sly) (sly-connect host port))))

(defun emacs-with-nyxt-connect (host port)
  "Connect `cl-ide' to HOST and PORT ignoring version mismatches."
  (emacs-with-nyxt--connect host port)
  (while (not (emacs-with-nyxt-connected-p))
    (message "Starting %s connection..." cl-ide)
    (sleep-for emacs-with-nyxt-delay)))

(defun emacs-with-nyxt-eval (string)
  "Send STRING to `cl-ide'."
  (cond
   ((eq cl-ide 'slime) (slime-repl-eval-string string))
   ((eq cl-ide 'sly) (sly-eval `(slynk:interactive-eval-region ,string)))))

(defun emacs-with-nyxt-send-sexps (&rest s-exps)
  "Evaluate S-EXPS with Nyxt `cl-ide' session."
  (let ((s-exps-string (s-join "" (--map (prin1-to-string it) s-exps))))
    (defun true (&rest args) 't)
    (if (emacs-with-nyxt-connected-p)
        (emacs-with-nyxt-eval s-exps-string)
      (error (format "%s is not connected to Nyxt. Run `emacs-with-nyxt-start-and-connect-to-nyxt' first" cl-ide)))))

(after! org
  (add-to-list
   'org-capture-templates
   `("N" "Web link" entry (file+headline ,(car org-agenda-files) "Links to read later")
     "* TODO %?%a :readings: \nSCHEDULED: %(org-insert-time-stamp (org-read-date nil t \"Fri\"))\n"
     :immediate-finish t :empty-lines 2)))

(defun on/slug-string (title)  (let ((slug-trim-chars '(;; Combining Diacritical Marks https://www.unicode.org/charts/PDF/U0300.pdf
                                                        768 ; U+0300 COMBINING GRAVE ACCENT
                                                        769 ; U+0301 COMBINING ACUTE ACCENT
                                                        770 ; U+0302 COMBINING CIRCUMFLEX ACCENT
                                                        771 ; U+0303 COMBINING TILDE
                                                        772 ; U+0304 COMBINING MACRON
                                                        774 ; U+0306 COMBINING BREVE
                                                        775 ; U+0307 COMBINING DOT ABOVE
                                                        776 ; U+0308 COMBINING DIAERESIS
                                                        777 ; U+0309 COMBINING HOOK ABOVE
                                                        778 ; U+030A COMBINING RING ABOVE
                                                        780 ; U+030C COMBINING CARON
                                                        795 ; U+031B COMBINING HORN
                                                        803 ; U+0323 COMBINING DOT BELOW
                                                        804 ; U+0324 COMBINING DIAERESIS BELOW
                                                        805 ; U+0325 COMBINING RING BELOW
                                                        807 ; U+0327 COMBINING CEDILLA
                                                        813 ; U+032D COMBINING CIRCUMFLEX ACCENT BELOW
                                                        814 ; U+032E COMBINING BREVE BELOW
                                                        816 ; U+0330 COMBINING TILDE BELOW
                                                        817 ; U+0331 COMBINING MACRON BELOW
                                                        )))
                                 (cl-flet* ((nonspacing-mark-p (char)
                                                               (memq char slug-trim-chars))
                                            (strip-nonspacing-marks (s)
                                                                    (ucs-normalize-NFC-string
                                                                     (apply #'string (seq-remove #'nonspacing-mark-p
                                                                                                 (ucs-normalize-NFD-string s)))))
                                            (cl-replace (title pair)
                                                        (replace-regexp-in-string (car pair) (cdr pair) title)))
                                   (let* ((pairs `(("[^[:alnum:][:digit:]]" . "_") ;; convert anything not alphanumeric
                                                   ("__*" . "_") ;; remove sequential underscores
                                                   ("^_" . "") ;; remove starting underscore
                                                   ("_$" . ""))) ;; remove ending underscore
                                          (slug (-reduce-from #'cl-replace (strip-nonspacing-marks title) pairs)))
                                     (downcase slug)))))

(defun on/make-filepath (title now &optional zone)
  "Make filename from note TITLE and NOW time (assumed in the current time ZONE)."
  (concat
   org-roam-directory
   (format-time-string "%Y%m%d%H%M%S_" now (or zone (current-time-zone)))
   (s-truncate 70 (on/slug-string title) "")
   ".org"))

(defun on/insert-org-roam-file (file-path title &optional links sources text quote)
  "Insert org roam file in FILE-PATH with TITLE, LINKS, SOURCES, TEXT, QUOTE."
  (with-temp-file file-path
    (insert
     "* " title "\n"
     "\n"
     "- tags :: " (--reduce (concat acc ", " it) links) "\n"
     (if sources (concat "- source :: " (--reduce (concat acc ", " it) sources) "\n") "")
     "\n"
     (if text text "")
     "\n"
     "\n"
     (if quote
         (concat "#+begin_src text \n"
                 quote "\n"
                 "#+end_src")
       "")))
  (with-file file-path
             (org-id-get-create)
             (save-buffer)))

(defun emacs-with-nyxt-current-package ()
  "Return current package set for `cl-ide'."
  (cond
   ((eq cl-ide 'slime) (slime-current-package))
   ((eq cl-ide 'sly) (with-current-buffer (sly-mrepl--find-buffer) (sly-current-package)))))

(defun emacs-with-nyxt-start-and-connect-to-nyxt (&optional no-maximize)
  "Start Nyxt with swank capabilities. Optionally skip window maximization with NO-MAXIMIZE."
  (interactive)
  (async-shell-command (format "/usr/bin/nyxt" ;; "nyxt -e \"(nyxt-user::start-swank)\""
                               ))
  (while (not (emacs-with-nyxt-connected-p))
    (message (format "Starting %s connection..." cl-ide))
    (ignore-errors (emacs-with-nyxt-connect "localhost" "1984"))
    (sleep-for emacs-with-nyxt-delay))
  (while (not (ignore-errors (string= "NYXT-USER" (upcase (emacs-with-nyxt-current-package)))))
    (progn (message "Setting %s package to NYXT-USER..." cl-ide)
           (sleep-for emacs-with-nyxt-delay)))
  (emacs-with-nyxt-send-sexps
   `(load "~/quicklisp/setup.lisp")
   `(defun replace-all (string part replacement &key (test #'char=))
      "Return a new string in which all the occurences of the part is replaced with replacement."
      (with-output-to-string (out)
                             (loop with part-length = (length part)
                                   for old-pos = 0 then (+ pos part-length)
                                   for pos = (search part string
                                                     :start2 old-pos
                                                     :test test)
                                   do (write-string string out
                                                    :start old-pos
                                                    :end (or pos (length string)))
                                   when pos do (write-string replacement out)
                                   while pos)))

   `(defun eval-in-emacs (&rest s-exps)
      "Evaluate S-EXPS with emacsclient."
      (let ((s-exps-string (replace-all
                            (write-to-string
                             `(progn ,@s-exps) :case :downcase)
                            ;; Discard the package prefix.
                            "nyxt::" "")))
        (format *error-output* "Sending to Emacs:~%~a~%" s-exps-string)
        (uiop:run-program
         (list "emacsclient" "--eval" s-exps-string))))
   `(ql:quickload "cl-qrencode")
   `(define-command-global my/make-current-url-qr-code () ; this is going to be redundant: https://nyxt.atlas.engineer/article/qr-url.org
      "Something else."
      (when (equal (mode-name (current-buffer)) 'web-buffer))
      (progn
        (cl-qrencode:encode-png (quri:render-uri (url (current-buffer))) :fpath "/tmp/qrcode.png")
        (uiop:run-program (list "nyxt" "/tmp/qrcode.png"))))
   '(define-command-global my/open-html-in-emacs ()
      "Open buffer html in Emacs."
      (when (equal (mode-name (current-buffer)) 'web-buffer))
      (with-open-file
       (file "/tmp/temp-nyxt.html" :direction :output
             :if-exists :supersede
             :if-does-not-exist :create)
       (write-string (ffi-buffer-get-document (current-buffer)) file))
      (eval-in-emacs
       `(progn (switch-to-buffer
                (get-buffer-create ,(render-url (url (current-buffer)))))
               (erase-buffer)
               (insert-file-contents-literally "/tmp/temp-nyxt.html")
               (html-mode)
               (indent-region (point-min) (point-max))))
      (delete-file "/tmp/temp-nyxt.html"))

   ;; from @aartaka https://www.reddit.com/r/Nyxt/comments/ock3tu/is_there_something_like_mx_or_esc_in_nyxt/h3wkipl?utm_source=share&utm_medium=web2x&context=3
   `(define-command-global eval-expression ()
      "Prompt for the expression and evaluate it, echoing result to the `message-area'."
      (let ((expression-string
             ;; Read an arbitrary expression. No error checking, though.
             (first (prompt :prompt "Expression to evaluate"
                            :sources (list (make-instance 'prompter:raw-source))))))
        ;; Message the thing to the message-area down below.
        (echo "~S" (eval (read-from-string expression-string)))))

   `(define-configuration nyxt/web-mode:web-mode
      ;; Bind eval-expression to M-:, but only in emacs-mode.
      ((keymap-scheme (let ((scheme %slot-default%))
                        (keymap:define-key (gethash scheme:emacs scheme)
                                           "M-:" 'eval-expression)
                        scheme))))
   `(defun emacs-with-nyxt-capture-link ()
      (let ((url (quri:render-uri (url (current-buffer)))))
        (if (str:containsp "youtu" url)
            (str:concat
             url
             "&t="
             (write-to-string
              (floor
               (ffi-buffer-evaluate-javascript (current-buffer)
                                               (ps:ps
                                                (ps:chain document
                                                          (get-element-by-id "movie_player")
                                                          (get-current-time))))))
             "s")
          url)))
   `(define-command-global org-capture ()
      "Org-capture current page."
      (eval-in-emacs
       `(let ((org-link-parameters
               (list (list "nyxt"
                           :store
                           (lambda ()
                             (org-store-link-props
                              :type "nyxt"
                              :link ,(emacs-with-nyxt-capture-link)
                              :description ,(title (current-buffer))))))))
          (org-capture nil "wN"))
       (echo "Note stored!")))
   `(define-command-global org-roam-capture ()
      "Org-capture current page."
      (let ((quote (%copy))
            (link (emacs-with-nyxt-capture-link))
            (title (prompt
                    :input (title (current-buffer))
                    :prompt "Title of note:"
                    :sources (list (make-instance 'prompter:raw-source))))
            (text (prompt
                   :input ""
                   :prompt "Note to take:"
                   :sources (list (make-instance 'prompter:raw-source)))))
        (eval-in-emacs
         `(let ((file (on/make-filepath ,(car title) (current-time))))
            (on/insert-org-roam-file
             file
             ,(car title)
             nil
             (list ,link)
             ,(car text)
             ,quote)
            (find-file file)
            (org-id-get-create)))
        (echo "Org Roam Note stored!")))
   `(define-configuration nyxt/web-mode:web-mode
      ;; Bind org-capture to C-o-c, but only in emacs-mode.
      ((keymap-scheme (let ((scheme %slot-default%))
                        (keymap:define-key (gethash scheme:emacs scheme)
                                           "C-c o c" 'org-capture)
                        scheme))))
   `(define-configuration nyxt/web-mode:web-mode
      ;; Bind org-roam-capture to C-c n f, but only in emacs-mode.
      ((keymap-scheme (let ((scheme %slot-default%))
                        (keymap:define-key (gethash scheme:emacs scheme)
                                           "C-c n f" 'org-roam-capture)
                        scheme))))
   )
  ;; (unless no-maximize
  ;;   (emacs-with-nyxt-send-sexps
  ;;    '(toggle-fullscreen)))
  )

(defun emacs-with-nyxt-browse-url-nyxt (url &optional buffer-title)
  "Open URL with Nyxt and optionally define BUFFER-TITLE."
  (interactive "sURL: ")
  (emacs-with-nyxt-send-sexps
   (append
    (list
     'buffer-load
     url)
    (if buffer-title
        `(:buffer (make-buffer :title ,buffer-title))
      nil))))

(defun emacs-with-nyxt-close-nyxt-connection ()
  "Close Nyxt connection."
  (interactive)
  (emacs-with-nyxt-send-sexps '(quit)))

(defun browse-url-nyxt (url &optional new-window)
  "Browse URL with Nyxt. NEW-WINDOW is ignored."
  (interactive "sURL: ")
  (unless (emacs-with-nyxt-connected-p) (emacs-with-nyxt-start-and-connect-to-nyxt))
  (emacs-with-nyxt-browse-url-nyxt url url))

(defun emacs-with-nyxt-search-first-in-nyxt-current-buffer (string)
  "Search current Nyxt buffer for STRING."
  (interactive "sString to search: ")
  (unless (emacs-with-nyxt-connected-p) (emacs-with-nyxt-start-and-connect-to-nyxt))
  (emacs-with-nyxt-send-sexps
   `(nyxt/web-mode::highlight-selected-hint
     :link-hint
     (car (nyxt/web-mode::matches-from-json
           (nyxt/web-mode::query-buffer :query ,string)))
     :scroll 't)))

(defun emacs-with-nyxt-make-qr-code-of-current-url ()
  "Open QR code of current url."
  (interactive)
  (if (file-exists-p "~/quicklisp/setup.lisp")
      (progn
        (unless (emacs-with-nyxt-connected-p) (emacs-with-nyxt-start-and-connect-to-nyxt))
        (emacs-with-nyxt-send-sexps
         '(ql:quickload "cl-qrencode")
         '(cl-qrencode:encode-png (quri:render-uri (url (current-buffer))) :fpath "/tmp/qrcode.png"))
        (find-file "/tmp/qrcode.png")
        (auto-revert-mode))
    (error "You cannot use this until you have Quicklisp installed! Check how to do that at: https://www.quicklisp.org/beta/#installation")))

(defun emacs-with-nyxt-get-nyxt-buffers ()
  "Return nyxt buffers."
  (when (emacs-with-nyxt-connected-p)
    (read
     (emacs-with-nyxt-send-sexps
      '(map 'list (lambda (el) (slot-value el 'title)) (buffer-list))))))

(defun emacs-with-nyxt-nyxt-switch-buffer (&optional title)
  "Interactively switch nyxt buffers.  If argument is provided switch to buffer with TITLE."
  (interactive)
  (if (emacs-with-nyxt-connected-p)
      (let ((title (or title (completing-read "Title: " (emacs-with-nyxt-get-nyxt-buffers)))))
        (emacs-with-nyxt-send-sexps
         `(switch-buffer :id (slot-value (find-if #'(lambda (el) (equal (slot-value el 'title) ,title)) (buffer-list)) 'id))))
    (error (format "%s is not connected to Nyxt. Run `emacs-with-nyxt-start-and-connect-to-nyxt' first" cl-ide))))

(defun emacs-with-nyxt-get-nyxt-commands ()
  "Return nyxt commands."
  (when (emacs-with-nyxt-connected-p)
    (read
     (emacs-with-nyxt-send-sexps
      `(let ((commands (make-instance 'command-source)))
         (map 'list (lambda (el) (slot-value el 'name)) (funcall (slot-value commands 'prompter:CONSTRUCTOR) commands)))))))

(defun emacs-with-nyxt-nyxt-run-command (&optional command)
  "Interactively run nyxt COMMAND."
  (interactive)
  (if (emacs-with-nyxt-connected-p)
      (let ((command (or command (completing-read "Execute command: " (emacs-with-nyxt-get-nyxt-commands)))))
        (emacs-with-nyxt-send-sexps `(nyxt::run-async ',(read command))))
    (error (format "%s is not connected to Nyxt. Run `emacs-with-nyxt-start-and-connect-to-nyxt' first" cl-ide))))

(defun emacs-with-nyxt-nyxt-take-over-prompt ()
  "Take over the nyxt prompt and let Emacs handle completions."
  (interactive)
  (emacs-with-nyxt-send-sexps
   `(progn
      (defun flatten (structure)
        (cond ((null structure) nil)
              ((atom structure) (list structure))
              (t (mapcan #'flatten structure))))

      (defun prompt (&REST args)
        (flet ((ensure-sources (specifiers)
                               (mapcar (lambda (source-specifier)
                                         (cond
                                          ((and (symbolp source-specifier)
                                                (c2cl:subclassp source-specifier 'source))
                                           (make-instance source-specifier))
                                          (t source-specifier)))
                                       (uiop:ensure-list specifiers))))
              (sleep 0.1)
              (let* ((promptstring (list (getf args :prompt)))
                     (sources (ensure-sources (getf args :sources)))
                     (names (mapcar (lambda (ol) (slot-value ol 'prompter:attributes)) (flatten (mapcar (lambda (el) (slot-value el 'PROMPTER::INITIAL-SUGGESTIONS)) sources))))
                     (testing (progn
                                (setq my-names names)
                                (setq my-prompt promptstring)))
                     (completed (read-from-string (eval-in-emacs `(emacs-with-nyxt-nyxt-complete ',promptstring ',names))))
                     (suggestion
                      (find-if (lambda (el) (equal completed (slot-value el 'PROMPTER::ATTRIBUTES))) (flatten (mapcar (lambda (el) (slot-value el 'PROMPTER::INITIAL-SUGGESTIONS)) sources))))
                     (selected-class (find-if (lambda (el) (find suggestion (slot-value el 'PROMPTER::INITIAL-SUGGESTIONS))) sources)))
                (if selected-class
                    (funcall (car (slot-value selected-class 'PROMPTER::ACTIONS)) (list (slot-value suggestion 'PROMPTER:VALUE)))
                  (funcall (car (slot-value (car sources) 'PROMPTER::ACTIONS)) (list completed)))))))))

(defun emacs-with-nyxt-nyxt-complete (prompt names)
  "Completion function for nyxt completion."
  (let* ((completions (--map (s-join "\t" (--map (s-join ": " it) it)) names))
         (completed-string (completing-read (s-append ": " (car prompt)) completions))
         (completed-index (-elem-index  completed-string completions)))
    (if (numberp completed-index)
        (nth completed-index names)
      completed-string)))

(defun emacs-with-nyxt-decode-command (encoded)
  "Decode an ENCODED link containing some Elisp. This is for the `.ag91' links."
  (--> encoded
       (s-split "/" it t)
       reverse
       car
       (s-split "\\." it t)
       car
       base64-decode-string
       read
       eval))

(defengine duckduckgo
  "https://duckduckgo.com/?q=%s"
  :keybinding "n"
  :browser 'browse-url-nyxt)

#+END_SRC
