icons_format = "{icon}"

[theme]
theme = "solarized-dark"
[theme.overrides]
idle_bg = "#123456"
idle_fg = "#abcdef"

[icons]
icons = "awesome4"
[icons.overrides]
bat = ["|E|", "|_|", "|=|", "|F|"]
bat_charging = "|^| "

[[block]]
block = "keyboard_layout"
driver="sway"

[[block]]
block = "cpu"
format = " $icon $barchart $utilization "

[[block]]
block = "temperature"
format = " $icon $max max "
format_alt = " $icon $min min, $max max, $average avg "
interval = 10
#chip = "*-isa-*"

# [[block]]
# block = "amd_gpu"
# format = " $icon $utilization "
# format_alt = " $icon MEM: $vram_used_percents ($vram_used/$vram_total) "
# interval = 1

[[block]]
block = "disk_space"
path = "/"
info_type = "available"
alert_unit = "GB"
interval = 20
warning = 20.0
alert = 10.0
format = " $icon root: $available.eng(w:2) "

[[block]]
block = "memory"
format = " $icon $mem_avail "
#format = " $icon $mem_total_used_percents.eng(w:2) "
#format_alt = " $icon_swap $swap_used_percents.eng(w:2) "

[[block]]
block = "bluetooth"
mac = "50:C2:E8:D5:58:BE"
#disconnected_format = ""
format = " $icon "
[block.battery_state]
"0..20" = "critical"
"21..70" = "warning"
"71..100" = "good"

[[block]]
block = "net"
device = "enp2s0"
format = " $icon $ip "
format_alt = " $icon $ip $speed_down $speed_up "

# [[block]]
# block = "external_ip"
# format = " $ip $country_code "

[[block]]
block = "time"
interval = 5
format = " $timestamp.datetime(f:'%a %d/%m %R') "
